// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/transactions.proto

package transactions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_INCOME      TransactionType = 1
	TransactionType_TRANSACTION_TYPE_EXPENSE     TransactionType = 2
	TransactionType_TRANSACTION_TYPE_TRANSFER    TransactionType = 3
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_INCOME",
		2: "TRANSACTION_TYPE_EXPENSE",
		3: "TRANSACTION_TYPE_TRANSFER",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_INCOME":      1,
		"TRANSACTION_TYPE_EXPENSE":     2,
		"TRANSACTION_TYPE_TRANSFER":    3,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transactions_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_transactions_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

type TransactionCategory int32

const (
	TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED       TransactionCategory = 0
	TransactionCategory_TRANSACTION_CATEGORY_SALARY            TransactionCategory = 1
	TransactionCategory_TRANSACTION_CATEGORY_INVESTMENT_INCOME TransactionCategory = 2
	TransactionCategory_TRANSACTION_CATEGORY_FOOD              TransactionCategory = 3
	TransactionCategory_TRANSACTION_CATEGORY_TRANSPORT         TransactionCategory = 4
	TransactionCategory_TRANSACTION_CATEGORY_UTILITIES         TransactionCategory = 5
	TransactionCategory_TRANSACTION_CATEGORY_ENTERTAINMENT     TransactionCategory = 6
	TransactionCategory_TRANSACTION_CATEGORY_SHOPPING          TransactionCategory = 7
	TransactionCategory_TRANSACTION_CATEGORY_HEALTHCARE        TransactionCategory = 8
	TransactionCategory_TRANSACTION_CATEGORY_EDUCATION         TransactionCategory = 9
	TransactionCategory_TRANSACTION_CATEGORY_TRAVEL            TransactionCategory = 10
	TransactionCategory_TRANSACTION_CATEGORY_HOUSING           TransactionCategory = 11
	TransactionCategory_TRANSACTION_CATEGORY_INSURANCE         TransactionCategory = 12
	TransactionCategory_TRANSACTION_CATEGORY_TAXES             TransactionCategory = 13
	TransactionCategory_TRANSACTION_CATEGORY_GIFTS             TransactionCategory = 14
	TransactionCategory_TRANSACTION_CATEGORY_TRANSFER          TransactionCategory = 15
	TransactionCategory_TRANSACTION_CATEGORY_OTHER             TransactionCategory = 16
)

// Enum value maps for TransactionCategory.
var (
	TransactionCategory_name = map[int32]string{
		0:  "TRANSACTION_CATEGORY_UNSPECIFIED",
		1:  "TRANSACTION_CATEGORY_SALARY",
		2:  "TRANSACTION_CATEGORY_INVESTMENT_INCOME",
		3:  "TRANSACTION_CATEGORY_FOOD",
		4:  "TRANSACTION_CATEGORY_TRANSPORT",
		5:  "TRANSACTION_CATEGORY_UTILITIES",
		6:  "TRANSACTION_CATEGORY_ENTERTAINMENT",
		7:  "TRANSACTION_CATEGORY_SHOPPING",
		8:  "TRANSACTION_CATEGORY_HEALTHCARE",
		9:  "TRANSACTION_CATEGORY_EDUCATION",
		10: "TRANSACTION_CATEGORY_TRAVEL",
		11: "TRANSACTION_CATEGORY_HOUSING",
		12: "TRANSACTION_CATEGORY_INSURANCE",
		13: "TRANSACTION_CATEGORY_TAXES",
		14: "TRANSACTION_CATEGORY_GIFTS",
		15: "TRANSACTION_CATEGORY_TRANSFER",
		16: "TRANSACTION_CATEGORY_OTHER",
	}
	TransactionCategory_value = map[string]int32{
		"TRANSACTION_CATEGORY_UNSPECIFIED":       0,
		"TRANSACTION_CATEGORY_SALARY":            1,
		"TRANSACTION_CATEGORY_INVESTMENT_INCOME": 2,
		"TRANSACTION_CATEGORY_FOOD":              3,
		"TRANSACTION_CATEGORY_TRANSPORT":         4,
		"TRANSACTION_CATEGORY_UTILITIES":         5,
		"TRANSACTION_CATEGORY_ENTERTAINMENT":     6,
		"TRANSACTION_CATEGORY_SHOPPING":          7,
		"TRANSACTION_CATEGORY_HEALTHCARE":        8,
		"TRANSACTION_CATEGORY_EDUCATION":         9,
		"TRANSACTION_CATEGORY_TRAVEL":            10,
		"TRANSACTION_CATEGORY_HOUSING":           11,
		"TRANSACTION_CATEGORY_INSURANCE":         12,
		"TRANSACTION_CATEGORY_TAXES":             13,
		"TRANSACTION_CATEGORY_GIFTS":             14,
		"TRANSACTION_CATEGORY_TRANSFER":          15,
		"TRANSACTION_CATEGORY_OTHER":             16,
	}
)

func (x TransactionCategory) Enum() *TransactionCategory {
	p := new(TransactionCategory)
	*p = x
	return p
}

func (x TransactionCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transactions_proto_enumTypes[1].Descriptor()
}

func (TransactionCategory) Type() protoreflect.EnumType {
	return &file_proto_transactions_proto_enumTypes[1]
}

func (x TransactionCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionCategory.Descriptor instead.
func (TransactionCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{1}
}

type Transaction struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Id                     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                 string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubAccountId           string                 `protobuf:"bytes,3,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Amount                 float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency               string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Type                   TransactionType        `protobuf:"varint,6,opt,name=type,proto3,enum=transactions.TransactionType" json:"type,omitempty"`
	Category               TransactionCategory    `protobuf:"varint,7,opt,name=category,proto3,enum=transactions.TransactionCategory" json:"category,omitempty"`
	CustomCategory         string                 `protobuf:"bytes,8,opt,name=custom_category,json=customCategory,proto3" json:"custom_category,omitempty"`
	Description            string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Merchant               string                 `protobuf:"bytes,10,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Date                   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt              *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt              *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata               map[string]string      `protobuf:"bytes,14,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TransferToSubAccountId string                 `protobuf:"bytes,15,opt,name=transfer_to_sub_account_id,json=transferToSubAccountId,proto3" json:"transfer_to_sub_account_id,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetCategory() TransactionCategory {
	if x != nil {
		return x.Category
	}
	return TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED
}

func (x *Transaction) GetCustomCategory() string {
	if x != nil {
		return x.CustomCategory
	}
	return ""
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *Transaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Transaction) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Transaction) GetTransferToSubAccountId() string {
	if x != nil {
		return x.TransferToSubAccountId
	}
	return ""
}

type CreateTransactionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubAccountId           string                 `protobuf:"bytes,2,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Amount                 float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency               string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Type                   TransactionType        `protobuf:"varint,5,opt,name=type,proto3,enum=transactions.TransactionType" json:"type,omitempty"`
	Category               TransactionCategory    `protobuf:"varint,6,opt,name=category,proto3,enum=transactions.TransactionCategory" json:"category,omitempty"`
	CustomCategory         string                 `protobuf:"bytes,7,opt,name=custom_category,json=customCategory,proto3" json:"custom_category,omitempty"`
	Description            string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Merchant               string                 `protobuf:"bytes,9,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Date                   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=date,proto3" json:"date,omitempty"`
	TransferToSubAccountId string                 `protobuf:"bytes,11,opt,name=transfer_to_sub_account_id,json=transferToSubAccountId,proto3" json:"transfer_to_sub_account_id,omitempty"`
	Metadata               map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateTransactionRequest) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *CreateTransactionRequest) GetCategory() TransactionCategory {
	if x != nil {
		return x.Category
	}
	return TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED
}

func (x *CreateTransactionRequest) GetCustomCategory() string {
	if x != nil {
		return x.CustomCategory
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *CreateTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *CreateTransactionRequest) GetTransferToSubAccountId() string {
	if x != nil {
		return x.TransferToSubAccountId
	}
	return ""
}

func (x *CreateTransactionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubAccountId  string                 `protobuf:"bytes,2,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortDesc      bool                   `protobuf:"varint,6,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_proto_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *ListTransactionsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListTransactionsRequest) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListTransactionsRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_proto_transactions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{4}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateTransactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Category       TransactionCategory    `protobuf:"varint,4,opt,name=category,proto3,enum=transactions.TransactionCategory" json:"category,omitempty"`
	CustomCategory string                 `protobuf:"bytes,5,opt,name=custom_category,json=customCategory,proto3" json:"custom_category,omitempty"`
	Description    string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Merchant       string                 `protobuf:"bytes,7,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCategory() TransactionCategory {
	if x != nil {
		return x.Category
	}
	return TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED
}

func (x *UpdateTransactionRequest) GetCustomCategory() string {
	if x != nil {
		return x.CustomCategory
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTransactionRequest) GetMerchant() string {
	if x != nil {
		return x.Merchant
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetTransactionsByDateRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	SubAccountId  string                 `protobuf:"bytes,4,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByDateRangeRequest) Reset() {
	*x = GetTransactionsByDateRangeRequest{}
	mi := &file_proto_transactions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByDateRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByDateRangeRequest) ProtoMessage() {}

func (x *GetTransactionsByDateRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByDateRangeRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByDateRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{7}
}

func (x *GetTransactionsByDateRangeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionsByDateRangeRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTransactionsByDateRangeRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetTransactionsByDateRangeRequest) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *GetTransactionsByDateRangeRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsByDateRangeRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTransactionsByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category      TransactionCategory    `protobuf:"varint,2,opt,name=category,proto3,enum=transactions.TransactionCategory" json:"category,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsByCategoryRequest) Reset() {
	*x = GetTransactionsByCategoryRequest{}
	mi := &file_proto_transactions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsByCategoryRequest) ProtoMessage() {}

func (x *GetTransactionsByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsByCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionsByCategoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionsByCategoryRequest) GetCategory() TransactionCategory {
	if x != nil {
		return x.Category
	}
	return TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED
}

func (x *GetTransactionsByCategoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTransactionsByCategoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetTransactionsByCategoryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTransactionsByCategoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetTransactionsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,4,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsSummaryRequest) Reset() {
	*x = GetTransactionsSummaryRequest{}
	mi := &file_proto_transactions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsSummaryRequest) ProtoMessage() {}

func (x *GetTransactionsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionsSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTransactionsSummaryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetTransactionsSummaryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetTransactionsSummaryRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type TransactionsSummaryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome      float64                `protobuf:"fixed64,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpenses    float64                `protobuf:"fixed64,2,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	NetFlow          float64                `protobuf:"fixed64,3,opt,name=net_flow,json=netFlow,proto3" json:"net_flow,omitempty"`
	Currency         string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	ByCategory       map[string]float64     `protobuf:"bytes,5,rep,name=by_category,json=byCategory,proto3" json:"by_category,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	TransactionCount int32                  `protobuf:"varint,6,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionsSummaryResponse) Reset() {
	*x = TransactionsSummaryResponse{}
	mi := &file_proto_transactions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionsSummaryResponse) ProtoMessage() {}

func (x *TransactionsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionsSummaryResponse.ProtoReflect.Descriptor instead.
func (*TransactionsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionsSummaryResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *TransactionsSummaryResponse) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *TransactionsSummaryResponse) GetNetFlow() float64 {
	if x != nil {
		return x.NetFlow
	}
	return 0
}

func (x *TransactionsSummaryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionsSummaryResponse) GetByCategory() map[string]float64 {
	if x != nil {
		return x.ByCategory
	}
	return nil
}

func (x *TransactionsSummaryResponse) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

type CategorizeTransactionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Category       TransactionCategory    `protobuf:"varint,3,opt,name=category,proto3,enum=transactions.TransactionCategory" json:"category,omitempty"`
	CustomCategory string                 `protobuf:"bytes,4,opt,name=custom_category,json=customCategory,proto3" json:"custom_category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategorizeTransactionRequest) Reset() {
	*x = CategorizeTransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategorizeTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategorizeTransactionRequest) ProtoMessage() {}

func (x *CategorizeTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategorizeTransactionRequest.ProtoReflect.Descriptor instead.
func (*CategorizeTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{11}
}

func (x *CategorizeTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CategorizeTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CategorizeTransactionRequest) GetCategory() TransactionCategory {
	if x != nil {
		return x.Category
	}
	return TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED
}

func (x *CategorizeTransactionRequest) GetCustomCategory() string {
	if x != nil {
		return x.CustomCategory
	}
	return ""
}

type BulkCategorizeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionIds []string               `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	Category       TransactionCategory    `protobuf:"varint,3,opt,name=category,proto3,enum=transactions.TransactionCategory" json:"category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkCategorizeRequest) Reset() {
	*x = BulkCategorizeRequest{}
	mi := &file_proto_transactions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCategorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCategorizeRequest) ProtoMessage() {}

func (x *BulkCategorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCategorizeRequest.ProtoReflect.Descriptor instead.
func (*BulkCategorizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{12}
}

func (x *BulkCategorizeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BulkCategorizeRequest) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

func (x *BulkCategorizeRequest) GetCategory() TransactionCategory {
	if x != nil {
		return x.Category
	}
	return TransactionCategory_TRANSACTION_CATEGORY_UNSPECIFIED
}

type BulkCategorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCategorizeResponse) Reset() {
	*x = BulkCategorizeResponse{}
	mi := &file_proto_transactions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCategorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCategorizeResponse) ProtoMessage() {}

func (x *BulkCategorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCategorizeResponse.ProtoReflect.Descriptor instead.
func (*BulkCategorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{13}
}

func (x *BulkCategorizeResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *BulkCategorizeResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

var File_proto_transactions_proto protoreflect.FileDescriptor

const file_proto_transactions_proto_rawDesc = "" +
	"\n" +
	"\x18proto/transactions.proto\x12\ftransactions\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x05\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_account_id\x18\x03 \x01(\tR\fsubAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x121\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1d.transactions.TransactionTypeR\x04type\x12=\n" +
	"\bcategory\x18\a \x01(\x0e2!.transactions.TransactionCategoryR\bcategory\x12'\n" +
	"\x0fcustom_category\x18\b \x01(\tR\x0ecustomCategory\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1a\n" +
	"\bmerchant\x18\n" +
	" \x01(\tR\bmerchant\x12.\n" +
	"\x04date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12C\n" +
	"\bmetadata\x18\x0e \x03(\v2'.transactions.Transaction.MetadataEntryR\bmetadata\x12:\n" +
	"\x1atransfer_to_sub_account_id\x18\x0f \x01(\tR\x16transferToSubAccountId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe1\x04\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_account_id\x18\x02 \x01(\tR\fsubAccountId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x121\n" +
	"\x04type\x18\x05 \x01(\x0e2\x1d.transactions.TransactionTypeR\x04type\x12=\n" +
	"\bcategory\x18\x06 \x01(\x0e2!.transactions.TransactionCategoryR\bcategory\x12'\n" +
	"\x0fcustom_category\x18\a \x01(\tR\x0ecustomCategory\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1a\n" +
	"\bmerchant\x18\t \x01(\tR\bmerchant\x12.\n" +
	"\x04date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12:\n" +
	"\x1atransfer_to_sub_account_id\x18\v \x01(\tR\x16transferToSubAccountId\x12P\n" +
	"\bmetadata\x18\f \x03(\v24.transactions.CreateTransactionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"@\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xbf\x01\n" +
	"\x17ListTransactionsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_account_id\x18\x02 \x01(\tR\fsubAccountId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\x06 \x01(\bR\bsortDesc\"\xa0\x01\n" +
	"\x18ListTransactionsResponse\x12=\n" +
	"\ftransactions\x18\x01 \x03(\v2\x19.transactions.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb1\x02\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12=\n" +
	"\bcategory\x18\x04 \x01(\x0e2!.transactions.TransactionCategoryR\bcategory\x12'\n" +
	"\x0fcustom_category\x18\x05 \x01(\tR\x0ecustomCategory\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmerchant\x18\a \x01(\tR\bmerchant\x12.\n" +
	"\x04date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"C\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x85\x02\n" +
	"!GetTransactionsByDateRangeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12$\n" +
	"\x0esub_account_id\x18\x04 \x01(\tR\fsubAccountId\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\x9d\x02\n" +
	" GetTransactionsByCategoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12=\n" +
	"\bcategory\x18\x02 \x01(\x0e2!.transactions.TransactionCategoryR\bcategory\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"\xcf\x01\n" +
	"\x1dGetTransactionsSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12#\n" +
	"\rbase_currency\x18\x04 \x01(\tR\fbaseCurrency\"\xe6\x02\n" +
	"\x1bTransactionsSummaryResponse\x12!\n" +
	"\ftotal_income\x18\x01 \x01(\x01R\vtotalIncome\x12%\n" +
	"\x0etotal_expenses\x18\x02 \x01(\x01R\rtotalExpenses\x12\x19\n" +
	"\bnet_flow\x18\x03 \x01(\x01R\anetFlow\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12Z\n" +
	"\vby_category\x18\x05 \x03(\v29.transactions.TransactionsSummaryResponse.ByCategoryEntryR\n" +
	"byCategory\x12+\n" +
	"\x11transaction_count\x18\x06 \x01(\x05R\x10transactionCount\x1a=\n" +
	"\x0fByCategoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xaf\x01\n" +
	"\x1cCategorizeTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12=\n" +
	"\bcategory\x18\x03 \x01(\x0e2!.transactions.TransactionCategoryR\bcategory\x12'\n" +
	"\x0fcustom_category\x18\x04 \x01(\tR\x0ecustomCategory\"\x98\x01\n" +
	"\x15BulkCategorizeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12'\n" +
	"\x0ftransaction_ids\x18\x02 \x03(\tR\x0etransactionIds\x12=\n" +
	"\bcategory\x18\x03 \x01(\x0e2!.transactions.TransactionCategoryR\bcategory\"\\\n" +
	"\x16BulkCategorizeResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds*\x8d\x01\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_INCOME\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_EXPENSE\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_TRANSFER\x10\x03*\xed\x04\n" +
	"\x13TransactionCategory\x12$\n" +
	" TRANSACTION_CATEGORY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRANSACTION_CATEGORY_SALARY\x10\x01\x12*\n" +
	"&TRANSACTION_CATEGORY_INVESTMENT_INCOME\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_CATEGORY_FOOD\x10\x03\x12\"\n" +
	"\x1eTRANSACTION_CATEGORY_TRANSPORT\x10\x04\x12\"\n" +
	"\x1eTRANSACTION_CATEGORY_UTILITIES\x10\x05\x12&\n" +
	"\"TRANSACTION_CATEGORY_ENTERTAINMENT\x10\x06\x12!\n" +
	"\x1dTRANSACTION_CATEGORY_SHOPPING\x10\a\x12#\n" +
	"\x1fTRANSACTION_CATEGORY_HEALTHCARE\x10\b\x12\"\n" +
	"\x1eTRANSACTION_CATEGORY_EDUCATION\x10\t\x12\x1f\n" +
	"\x1bTRANSACTION_CATEGORY_TRAVEL\x10\n" +
	"\x12 \n" +
	"\x1cTRANSACTION_CATEGORY_HOUSING\x10\v\x12\"\n" +
	"\x1eTRANSACTION_CATEGORY_INSURANCE\x10\f\x12\x1e\n" +
	"\x1aTRANSACTION_CATEGORY_TAXES\x10\r\x12\x1e\n" +
	"\x1aTRANSACTION_CATEGORY_GIFTS\x10\x0e\x12!\n" +
	"\x1dTRANSACTION_CATEGORY_TRANSFER\x10\x0f\x12\x1e\n" +
	"\x1aTRANSACTION_CATEGORY_OTHER\x10\x102\xea\a\n" +
	"\x13TransactionsService\x12V\n" +
	"\x11CreateTransaction\x12&.transactions.CreateTransactionRequest\x1a\x19.transactions.Transaction\x12P\n" +
	"\x0eGetTransaction\x12#.transactions.GetTransactionRequest\x1a\x19.transactions.Transaction\x12a\n" +
	"\x10ListTransactions\x12%.transactions.ListTransactionsRequest\x1a&.transactions.ListTransactionsResponse\x12V\n" +
	"\x11UpdateTransaction\x12&.transactions.UpdateTransactionRequest\x1a\x19.transactions.Transaction\x12S\n" +
	"\x11DeleteTransaction\x12&.transactions.DeleteTransactionRequest\x1a\x16.google.protobuf.Empty\x12u\n" +
	"\x1aGetTransactionsByDateRange\x12/.transactions.GetTransactionsByDateRangeRequest\x1a&.transactions.ListTransactionsResponse\x12s\n" +
	"\x19GetTransactionsByCategory\x12..transactions.GetTransactionsByCategoryRequest\x1a&.transactions.ListTransactionsResponse\x12p\n" +
	"\x16GetTransactionsSummary\x12+.transactions.GetTransactionsSummaryRequest\x1a).transactions.TransactionsSummaryResponse\x12^\n" +
	"\x15CategorizeTransaction\x12*.transactions.CategorizeTransactionRequest\x1a\x19.transactions.Transaction\x12[\n" +
	"\x0eBulkCategorize\x12#.transactions.BulkCategorizeRequest\x1a$.transactions.BulkCategorizeResponseB?Z=github.com/radmickey/money-control/backend/proto/transactionsb\x06proto3"

var (
	file_proto_transactions_proto_rawDescOnce sync.Once
	file_proto_transactions_proto_rawDescData []byte
)

func file_proto_transactions_proto_rawDescGZIP() []byte {
	file_proto_transactions_proto_rawDescOnce.Do(func() {
		file_proto_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)))
	})
	return file_proto_transactions_proto_rawDescData
}

var file_proto_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_transactions_proto_goTypes = []any{
	(TransactionType)(0),                      // 0: transactions.TransactionType
	(TransactionCategory)(0),                  // 1: transactions.TransactionCategory
	(*Transaction)(nil),                       // 2: transactions.Transaction
	(*CreateTransactionRequest)(nil),          // 3: transactions.CreateTransactionRequest
	(*GetTransactionRequest)(nil),             // 4: transactions.GetTransactionRequest
	(*ListTransactionsRequest)(nil),           // 5: transactions.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),          // 6: transactions.ListTransactionsResponse
	(*UpdateTransactionRequest)(nil),          // 7: transactions.UpdateTransactionRequest
	(*DeleteTransactionRequest)(nil),          // 8: transactions.DeleteTransactionRequest
	(*GetTransactionsByDateRangeRequest)(nil), // 9: transactions.GetTransactionsByDateRangeRequest
	(*GetTransactionsByCategoryRequest)(nil),  // 10: transactions.GetTransactionsByCategoryRequest
	(*GetTransactionsSummaryRequest)(nil),     // 11: transactions.GetTransactionsSummaryRequest
	(*TransactionsSummaryResponse)(nil),       // 12: transactions.TransactionsSummaryResponse
	(*CategorizeTransactionRequest)(nil),      // 13: transactions.CategorizeTransactionRequest
	(*BulkCategorizeRequest)(nil),             // 14: transactions.BulkCategorizeRequest
	(*BulkCategorizeResponse)(nil),            // 15: transactions.BulkCategorizeResponse
	nil,                                       // 16: transactions.Transaction.MetadataEntry
	nil,                                       // 17: transactions.CreateTransactionRequest.MetadataEntry
	nil,                                       // 18: transactions.TransactionsSummaryResponse.ByCategoryEntry
	(*timestamppb.Timestamp)(nil),             // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                     // 20: google.protobuf.Empty
}
var file_proto_transactions_proto_depIdxs = []int32{
	0,  // 0: transactions.Transaction.type:type_name -> transactions.TransactionType
	1,  // 1: transactions.Transaction.category:type_name -> transactions.TransactionCategory
	19, // 2: transactions.Transaction.date:type_name -> google.protobuf.Timestamp
	19, // 3: transactions.Transaction.created_at:type_name -> google.protobuf.Timestamp
	19, // 4: transactions.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	16, // 5: transactions.Transaction.metadata:type_name -> transactions.Transaction.MetadataEntry
	0,  // 6: transactions.CreateTransactionRequest.type:type_name -> transactions.TransactionType
	1,  // 7: transactions.CreateTransactionRequest.category:type_name -> transactions.TransactionCategory
	19, // 8: transactions.CreateTransactionRequest.date:type_name -> google.protobuf.Timestamp
	17, // 9: transactions.CreateTransactionRequest.metadata:type_name -> transactions.CreateTransactionRequest.MetadataEntry
	2,  // 10: transactions.ListTransactionsResponse.transactions:type_name -> transactions.Transaction
	1,  // 11: transactions.UpdateTransactionRequest.category:type_name -> transactions.TransactionCategory
	19, // 12: transactions.UpdateTransactionRequest.date:type_name -> google.protobuf.Timestamp
	19, // 13: transactions.GetTransactionsByDateRangeRequest.start_date:type_name -> google.protobuf.Timestamp
	19, // 14: transactions.GetTransactionsByDateRangeRequest.end_date:type_name -> google.protobuf.Timestamp
	1,  // 15: transactions.GetTransactionsByCategoryRequest.category:type_name -> transactions.TransactionCategory
	19, // 16: transactions.GetTransactionsByCategoryRequest.start_date:type_name -> google.protobuf.Timestamp
	19, // 17: transactions.GetTransactionsByCategoryRequest.end_date:type_name -> google.protobuf.Timestamp
	19, // 18: transactions.GetTransactionsSummaryRequest.start_date:type_name -> google.protobuf.Timestamp
	19, // 19: transactions.GetTransactionsSummaryRequest.end_date:type_name -> google.protobuf.Timestamp
	18, // 20: transactions.TransactionsSummaryResponse.by_category:type_name -> transactions.TransactionsSummaryResponse.ByCategoryEntry
	1,  // 21: transactions.CategorizeTransactionRequest.category:type_name -> transactions.TransactionCategory
	1,  // 22: transactions.BulkCategorizeRequest.category:type_name -> transactions.TransactionCategory
	3,  // 23: transactions.TransactionsService.CreateTransaction:input_type -> transactions.CreateTransactionRequest
	4,  // 24: transactions.TransactionsService.GetTransaction:input_type -> transactions.GetTransactionRequest
	5,  // 25: transactions.TransactionsService.ListTransactions:input_type -> transactions.ListTransactionsRequest
	7,  // 26: transactions.TransactionsService.UpdateTransaction:input_type -> transactions.UpdateTransactionRequest
	8,  // 27: transactions.TransactionsService.DeleteTransaction:input_type -> transactions.DeleteTransactionRequest
	9,  // 28: transactions.TransactionsService.GetTransactionsByDateRange:input_type -> transactions.GetTransactionsByDateRangeRequest
	10, // 29: transactions.TransactionsService.GetTransactionsByCategory:input_type -> transactions.GetTransactionsByCategoryRequest
	11, // 30: transactions.TransactionsService.GetTransactionsSummary:input_type -> transactions.GetTransactionsSummaryRequest
	13, // 31: transactions.TransactionsService.CategorizeTransaction:input_type -> transactions.CategorizeTransactionRequest
	14, // 32: transactions.TransactionsService.BulkCategorize:input_type -> transactions.BulkCategorizeRequest
	2,  // 33: transactions.TransactionsService.CreateTransaction:output_type -> transactions.Transaction
	2,  // 34: transactions.TransactionsService.GetTransaction:output_type -> transactions.Transaction
	6,  // 35: transactions.TransactionsService.ListTransactions:output_type -> transactions.ListTransactionsResponse
	2,  // 36: transactions.TransactionsService.UpdateTransaction:output_type -> transactions.Transaction
	20, // 37: transactions.TransactionsService.DeleteTransaction:output_type -> google.protobuf.Empty
	6,  // 38: transactions.TransactionsService.GetTransactionsByDateRange:output_type -> transactions.ListTransactionsResponse
	6,  // 39: transactions.TransactionsService.GetTransactionsByCategory:output_type -> transactions.ListTransactionsResponse
	12, // 40: transactions.TransactionsService.GetTransactionsSummary:output_type -> transactions.TransactionsSummaryResponse
	2,  // 41: transactions.TransactionsService.CategorizeTransaction:output_type -> transactions.Transaction
	15, // 42: transactions.TransactionsService.BulkCategorize:output_type -> transactions.BulkCategorizeResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_transactions_proto_init() }
func file_proto_transactions_proto_init() {
	if File_proto_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transactions_proto_goTypes,
		DependencyIndexes: file_proto_transactions_proto_depIdxs,
		EnumInfos:         file_proto_transactions_proto_enumTypes,
		MessageInfos:      file_proto_transactions_proto_msgTypes,
	}.Build()
	File_proto_transactions_proto = out.File
	file_proto_transactions_proto_goTypes = nil
	file_proto_transactions_proto_depIdxs = nil
}
