// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/insights.proto

package insights

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Snapshot struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalNetWorth  float64                `protobuf:"fixed64,3,opt,name=total_net_worth,json=totalNetWorth,proto3" json:"total_net_worth,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	AllocationData string                 `protobuf:"bytes,5,opt,name=allocation_data,json=allocationData,proto3" json:"allocation_data,omitempty"`
	Date           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_insights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{0}
}

func (x *Snapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Snapshot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Snapshot) GetTotalNetWorth() float64 {
	if x != nil {
		return x.TotalNetWorth
	}
	return 0
}

func (x *Snapshot) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Snapshot) GetAllocationData() string {
	if x != nil {
		return x.AllocationData
	}
	return ""
}

func (x *Snapshot) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Snapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetNetWorthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetWorthRequest) Reset() {
	*x = GetNetWorthRequest{}
	mi := &file_proto_insights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthRequest) ProtoMessage() {}

func (x *GetNetWorthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthRequest.ProtoReflect.Descriptor instead.
func (*GetNetWorthRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{1}
}

func (x *GetNetWorthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNetWorthRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type NetWorthResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalNetWorth     float64                `protobuf:"fixed64,1,opt,name=total_net_worth,json=totalNetWorth,proto3" json:"total_net_worth,omitempty"`
	Currency          string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Change_24H        float64                `protobuf:"fixed64,3,opt,name=change_24h,json=change24h,proto3" json:"change_24h,omitempty"`
	ChangePercent_24H float64                `protobuf:"fixed64,4,opt,name=change_percent_24h,json=changePercent24h,proto3" json:"change_percent_24h,omitempty"`
	Change_7D         float64                `protobuf:"fixed64,5,opt,name=change_7d,json=change7d,proto3" json:"change_7d,omitempty"`
	ChangePercent_7D  float64                `protobuf:"fixed64,6,opt,name=change_percent_7d,json=changePercent7d,proto3" json:"change_percent_7d,omitempty"`
	Change_30D        float64                `protobuf:"fixed64,7,opt,name=change_30d,json=change30d,proto3" json:"change_30d,omitempty"`
	ChangePercent_30D float64                `protobuf:"fixed64,8,opt,name=change_percent_30d,json=changePercent30d,proto3" json:"change_percent_30d,omitempty"`
	CalculatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NetWorthResponse) Reset() {
	*x = NetWorthResponse{}
	mi := &file_proto_insights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthResponse) ProtoMessage() {}

func (x *NetWorthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthResponse.ProtoReflect.Descriptor instead.
func (*NetWorthResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{2}
}

func (x *NetWorthResponse) GetTotalNetWorth() float64 {
	if x != nil {
		return x.TotalNetWorth
	}
	return 0
}

func (x *NetWorthResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *NetWorthResponse) GetChange_24H() float64 {
	if x != nil {
		return x.Change_24H
	}
	return 0
}

func (x *NetWorthResponse) GetChangePercent_24H() float64 {
	if x != nil {
		return x.ChangePercent_24H
	}
	return 0
}

func (x *NetWorthResponse) GetChange_7D() float64 {
	if x != nil {
		return x.Change_7D
	}
	return 0
}

func (x *NetWorthResponse) GetChangePercent_7D() float64 {
	if x != nil {
		return x.ChangePercent_7D
	}
	return 0
}

func (x *NetWorthResponse) GetChange_30D() float64 {
	if x != nil {
		return x.Change_30D
	}
	return 0
}

func (x *NetWorthResponse) GetChangePercent_30D() float64 {
	if x != nil {
		return x.ChangePercent_30D
	}
	return 0
}

func (x *NetWorthResponse) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

type GetNetWorthHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetWorthHistoryRequest) Reset() {
	*x = GetNetWorthHistoryRequest{}
	mi := &file_proto_insights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthHistoryRequest) ProtoMessage() {}

func (x *GetNetWorthHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetNetWorthHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{3}
}

func (x *GetNetWorthHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetNetWorthHistoryRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetNetWorthHistoryRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetNetWorthHistoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetNetWorthHistoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type NetWorthHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*NetWorthPoint       `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetWorthHistoryResponse) Reset() {
	*x = NetWorthHistoryResponse{}
	mi := &file_proto_insights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthHistoryResponse) ProtoMessage() {}

func (x *NetWorthHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthHistoryResponse.ProtoReflect.Descriptor instead.
func (*NetWorthHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{4}
}

func (x *NetWorthHistoryResponse) GetHistory() []*NetWorthPoint {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *NetWorthHistoryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type NetWorthPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetWorthPoint) Reset() {
	*x = NetWorthPoint{}
	mi := &file_proto_insights_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthPoint) ProtoMessage() {}

func (x *NetWorthPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthPoint.ProtoReflect.Descriptor instead.
func (*NetWorthPoint) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{5}
}

func (x *NetWorthPoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *NetWorthPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GetAllocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	GroupBy       string                 `protobuf:"bytes,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationRequest) Reset() {
	*x = GetAllocationRequest{}
	mi := &file_proto_insights_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationRequest) ProtoMessage() {}

func (x *GetAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationRequest.ProtoReflect.Descriptor instead.
func (*GetAllocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllocationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAllocationRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetAllocationRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

type AllocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocations   []*AllocationItem      `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	TotalValue    float64                `protobuf:"fixed64,2,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationResponse) Reset() {
	*x = AllocationResponse{}
	mi := &file_proto_insights_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationResponse) ProtoMessage() {}

func (x *AllocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationResponse.ProtoReflect.Descriptor instead.
func (*AllocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{7}
}

func (x *AllocationResponse) GetAllocations() []*AllocationItem {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *AllocationResponse) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *AllocationResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type AllocationItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationItem) Reset() {
	*x = AllocationItem{}
	mi := &file_proto_insights_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationItem) ProtoMessage() {}

func (x *AllocationItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationItem.ProtoReflect.Descriptor instead.
func (*AllocationItem) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{8}
}

func (x *AllocationItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AllocationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AllocationItem) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AllocationItem) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *AllocationItem) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type GetBalanceChangesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceChangesRequest) Reset() {
	*x = GetBalanceChangesRequest{}
	mi := &file_proto_insights_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceChangesRequest) ProtoMessage() {}

func (x *GetBalanceChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceChangesRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceChangesRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{9}
}

func (x *GetBalanceChangesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetBalanceChangesRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetBalanceChangesRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetBalanceChangesRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetBalanceChangesRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type BalanceChangesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Changes            []*BalanceChange       `protobuf:"bytes,1,rep,name=changes,proto3" json:"changes,omitempty"`
	TotalChange        float64                `protobuf:"fixed64,2,opt,name=total_change,json=totalChange,proto3" json:"total_change,omitempty"`
	TotalChangePercent float64                `protobuf:"fixed64,3,opt,name=total_change_percent,json=totalChangePercent,proto3" json:"total_change_percent,omitempty"`
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BalanceChangesResponse) Reset() {
	*x = BalanceChangesResponse{}
	mi := &file_proto_insights_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceChangesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChangesResponse) ProtoMessage() {}

func (x *BalanceChangesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChangesResponse.ProtoReflect.Descriptor instead.
func (*BalanceChangesResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{10}
}

func (x *BalanceChangesResponse) GetChanges() []*BalanceChange {
	if x != nil {
		return x.Changes
	}
	return nil
}

func (x *BalanceChangesResponse) GetTotalChange() float64 {
	if x != nil {
		return x.TotalChange
	}
	return 0
}

func (x *BalanceChangesResponse) GetTotalChangePercent() float64 {
	if x != nil {
		return x.TotalChangePercent
	}
	return 0
}

func (x *BalanceChangesResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type BalanceChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName     string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	StartingBalance float64                `protobuf:"fixed64,3,opt,name=starting_balance,json=startingBalance,proto3" json:"starting_balance,omitempty"`
	EndingBalance   float64                `protobuf:"fixed64,4,opt,name=ending_balance,json=endingBalance,proto3" json:"ending_balance,omitempty"`
	Change          float64                `protobuf:"fixed64,5,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent   float64                `protobuf:"fixed64,6,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BalanceChange) Reset() {
	*x = BalanceChange{}
	mi := &file_proto_insights_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChange) ProtoMessage() {}

func (x *BalanceChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChange.ProtoReflect.Descriptor instead.
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{11}
}

func (x *BalanceChange) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceChange) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *BalanceChange) GetStartingBalance() float64 {
	if x != nil {
		return x.StartingBalance
	}
	return 0
}

func (x *BalanceChange) GetEndingBalance() float64 {
	if x != nil {
		return x.EndingBalance
	}
	return 0
}

func (x *BalanceChange) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *BalanceChange) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

type GetTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	Metric        string                 `protobuf:"bytes,4,opt,name=metric,proto3" json:"metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendsRequest) Reset() {
	*x = GetTrendsRequest{}
	mi := &file_proto_insights_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendsRequest) ProtoMessage() {}

func (x *GetTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{12}
}

func (x *GetTrendsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetTrendsRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetTrendsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetTrendsRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

type TrendsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Metric         string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Period         string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	Data           []*TrendPoint          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Average        float64                `protobuf:"fixed64,4,opt,name=average,proto3" json:"average,omitempty"`
	Min            float64                `protobuf:"fixed64,5,opt,name=min,proto3" json:"min,omitempty"`
	Max            float64                `protobuf:"fixed64,6,opt,name=max,proto3" json:"max,omitempty"`
	TrendDirection string                 `protobuf:"bytes,7,opt,name=trend_direction,json=trendDirection,proto3" json:"trend_direction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TrendsResponse) Reset() {
	*x = TrendsResponse{}
	mi := &file_proto_insights_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendsResponse) ProtoMessage() {}

func (x *TrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendsResponse.ProtoReflect.Descriptor instead.
func (*TrendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{13}
}

func (x *TrendsResponse) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *TrendsResponse) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *TrendsResponse) GetData() []*TrendPoint {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TrendsResponse) GetAverage() float64 {
	if x != nil {
		return x.Average
	}
	return 0
}

func (x *TrendsResponse) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *TrendsResponse) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *TrendsResponse) GetTrendDirection() string {
	if x != nil {
		return x.TrendDirection
	}
	return ""
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Label         string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_proto_insights_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{14}
}

func (x *TrendPoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *TrendPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TrendPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type GetDashboardSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardSummaryRequest) Reset() {
	*x = GetDashboardSummaryRequest{}
	mi := &file_proto_insights_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardSummaryRequest) ProtoMessage() {}

func (x *GetDashboardSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{15}
}

func (x *GetDashboardSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetDashboardSummaryRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type DashboardSummaryResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	NetWorth                  float64                `protobuf:"fixed64,1,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	NetWorthChange_24H        float64                `protobuf:"fixed64,2,opt,name=net_worth_change_24h,json=netWorthChange24h,proto3" json:"net_worth_change_24h,omitempty"`
	NetWorthChangePercent_24H float64                `protobuf:"fixed64,3,opt,name=net_worth_change_percent_24h,json=netWorthChangePercent24h,proto3" json:"net_worth_change_percent_24h,omitempty"`
	TotalAssets               float64                `protobuf:"fixed64,4,opt,name=total_assets,json=totalAssets,proto3" json:"total_assets,omitempty"`
	TotalLiabilities          float64                `protobuf:"fixed64,5,opt,name=total_liabilities,json=totalLiabilities,proto3" json:"total_liabilities,omitempty"`
	MonthlyIncome             float64                `protobuf:"fixed64,6,opt,name=monthly_income,json=monthlyIncome,proto3" json:"monthly_income,omitempty"`
	MonthlyExpenses           float64                `protobuf:"fixed64,7,opt,name=monthly_expenses,json=monthlyExpenses,proto3" json:"monthly_expenses,omitempty"`
	MonthlySavings            float64                `protobuf:"fixed64,8,opt,name=monthly_savings,json=monthlySavings,proto3" json:"monthly_savings,omitempty"`
	SavingsRate               float64                `protobuf:"fixed64,9,opt,name=savings_rate,json=savingsRate,proto3" json:"savings_rate,omitempty"`
	TopAllocations            []*AllocationItem      `protobuf:"bytes,10,rep,name=top_allocations,json=topAllocations,proto3" json:"top_allocations,omitempty"`
	RecentTransactions        []*RecentTransaction   `protobuf:"bytes,11,rep,name=recent_transactions,json=recentTransactions,proto3" json:"recent_transactions,omitempty"`
	TopPerformers             []*TopPerformer        `protobuf:"bytes,12,rep,name=top_performers,json=topPerformers,proto3" json:"top_performers,omitempty"`
	Currency                  string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	CalculatedAt              *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DashboardSummaryResponse) Reset() {
	*x = DashboardSummaryResponse{}
	mi := &file_proto_insights_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardSummaryResponse) ProtoMessage() {}

func (x *DashboardSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardSummaryResponse.ProtoReflect.Descriptor instead.
func (*DashboardSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{16}
}

func (x *DashboardSummaryResponse) GetNetWorth() float64 {
	if x != nil {
		return x.NetWorth
	}
	return 0
}

func (x *DashboardSummaryResponse) GetNetWorthChange_24H() float64 {
	if x != nil {
		return x.NetWorthChange_24H
	}
	return 0
}

func (x *DashboardSummaryResponse) GetNetWorthChangePercent_24H() float64 {
	if x != nil {
		return x.NetWorthChangePercent_24H
	}
	return 0
}

func (x *DashboardSummaryResponse) GetTotalAssets() float64 {
	if x != nil {
		return x.TotalAssets
	}
	return 0
}

func (x *DashboardSummaryResponse) GetTotalLiabilities() float64 {
	if x != nil {
		return x.TotalLiabilities
	}
	return 0
}

func (x *DashboardSummaryResponse) GetMonthlyIncome() float64 {
	if x != nil {
		return x.MonthlyIncome
	}
	return 0
}

func (x *DashboardSummaryResponse) GetMonthlyExpenses() float64 {
	if x != nil {
		return x.MonthlyExpenses
	}
	return 0
}

func (x *DashboardSummaryResponse) GetMonthlySavings() float64 {
	if x != nil {
		return x.MonthlySavings
	}
	return 0
}

func (x *DashboardSummaryResponse) GetSavingsRate() float64 {
	if x != nil {
		return x.SavingsRate
	}
	return 0
}

func (x *DashboardSummaryResponse) GetTopAllocations() []*AllocationItem {
	if x != nil {
		return x.TopAllocations
	}
	return nil
}

func (x *DashboardSummaryResponse) GetRecentTransactions() []*RecentTransaction {
	if x != nil {
		return x.RecentTransactions
	}
	return nil
}

func (x *DashboardSummaryResponse) GetTopPerformers() []*TopPerformer {
	if x != nil {
		return x.TopPerformers
	}
	return nil
}

func (x *DashboardSummaryResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *DashboardSummaryResponse) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

type RecentTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentTransaction) Reset() {
	*x = RecentTransaction{}
	mi := &file_proto_insights_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentTransaction) ProtoMessage() {}

func (x *RecentTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentTransaction.ProtoReflect.Descriptor instead.
func (*RecentTransaction) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{17}
}

func (x *RecentTransaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecentTransaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecentTransaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RecentTransaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RecentTransaction) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RecentTransaction) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type TopPerformer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Change        float64                `protobuf:"fixed64,4,opt,name=change,proto3" json:"change,omitempty"`
	ChangePercent float64                `protobuf:"fixed64,5,opt,name=change_percent,json=changePercent,proto3" json:"change_percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopPerformer) Reset() {
	*x = TopPerformer{}
	mi := &file_proto_insights_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopPerformer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopPerformer) ProtoMessage() {}

func (x *TopPerformer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopPerformer.ProtoReflect.Descriptor instead.
func (*TopPerformer) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{18}
}

func (x *TopPerformer) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TopPerformer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TopPerformer) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TopPerformer) GetChange() float64 {
	if x != nil {
		return x.Change
	}
	return 0
}

func (x *TopPerformer) GetChangePercent() float64 {
	if x != nil {
		return x.ChangePercent
	}
	return 0
}

type GetCashFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	Period        string                 `protobuf:"bytes,3,opt,name=period,proto3" json:"period,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCashFlowRequest) Reset() {
	*x = GetCashFlowRequest{}
	mi := &file_proto_insights_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCashFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCashFlowRequest) ProtoMessage() {}

func (x *GetCashFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCashFlowRequest.ProtoReflect.Descriptor instead.
func (*GetCashFlowRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{19}
}

func (x *GetCashFlowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCashFlowRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetCashFlowRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetCashFlowRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetCashFlowRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type CashFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Periods       []*CashFlowPeriod      `protobuf:"bytes,1,rep,name=periods,proto3" json:"periods,omitempty"`
	TotalIncome   float64                `protobuf:"fixed64,2,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpenses float64                `protobuf:"fixed64,3,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	NetCashFlow   float64                `protobuf:"fixed64,4,opt,name=net_cash_flow,json=netCashFlow,proto3" json:"net_cash_flow,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFlowResponse) Reset() {
	*x = CashFlowResponse{}
	mi := &file_proto_insights_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFlowResponse) ProtoMessage() {}

func (x *CashFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFlowResponse.ProtoReflect.Descriptor instead.
func (*CashFlowResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{20}
}

func (x *CashFlowResponse) GetPeriods() []*CashFlowPeriod {
	if x != nil {
		return x.Periods
	}
	return nil
}

func (x *CashFlowResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *CashFlowResponse) GetTotalExpenses() float64 {
	if x != nil {
		return x.TotalExpenses
	}
	return 0
}

func (x *CashFlowResponse) GetNetCashFlow() float64 {
	if x != nil {
		return x.NetCashFlow
	}
	return 0
}

func (x *CashFlowResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CashFlowPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Income        float64                `protobuf:"fixed64,4,opt,name=income,proto3" json:"income,omitempty"`
	Expenses      float64                `protobuf:"fixed64,5,opt,name=expenses,proto3" json:"expenses,omitempty"`
	Net           float64                `protobuf:"fixed64,6,opt,name=net,proto3" json:"net,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CashFlowPeriod) Reset() {
	*x = CashFlowPeriod{}
	mi := &file_proto_insights_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CashFlowPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CashFlowPeriod) ProtoMessage() {}

func (x *CashFlowPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CashFlowPeriod.ProtoReflect.Descriptor instead.
func (*CashFlowPeriod) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{21}
}

func (x *CashFlowPeriod) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CashFlowPeriod) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *CashFlowPeriod) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *CashFlowPeriod) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *CashFlowPeriod) GetExpenses() float64 {
	if x != nil {
		return x.Expenses
	}
	return 0
}

func (x *CashFlowPeriod) GetNet() float64 {
	if x != nil {
		return x.Net
	}
	return 0
}

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_proto_insights_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{22}
}

func (x *CreateSnapshotRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSnapshotRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type GetSnapshotsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotsRequest) Reset() {
	*x = GetSnapshotsRequest{}
	mi := &file_proto_insights_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotsRequest) ProtoMessage() {}

func (x *GetSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{23}
}

func (x *GetSnapshotsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSnapshotsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetSnapshotsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *GetSnapshotsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetSnapshotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*Snapshot            `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotsResponse) Reset() {
	*x = GetSnapshotsResponse{}
	mi := &file_proto_insights_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotsResponse) ProtoMessage() {}

func (x *GetSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_insights_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_proto_insights_proto_rawDescGZIP(), []int{24}
}

func (x *GetSnapshotsResponse) GetSnapshots() []*Snapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

var File_proto_insights_proto protoreflect.FileDescriptor

const file_proto_insights_proto_rawDesc = "" +
	"\n" +
	"\x14proto/insights.proto\x12\binsights\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\bSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x0ftotal_net_worth\x18\x03 \x01(\x01R\rtotalNetWorth\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0fallocation_data\x18\x05 \x01(\tR\x0eallocationData\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"R\n" +
	"\x12GetNetWorthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\"\xfa\x02\n" +
	"\x10NetWorthResponse\x12&\n" +
	"\x0ftotal_net_worth\x18\x01 \x01(\x01R\rtotalNetWorth\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"change_24h\x18\x03 \x01(\x01R\tchange24h\x12,\n" +
	"\x12change_percent_24h\x18\x04 \x01(\x01R\x10changePercent24h\x12\x1b\n" +
	"\tchange_7d\x18\x05 \x01(\x01R\bchange7d\x12*\n" +
	"\x11change_percent_7d\x18\x06 \x01(\x01R\x0fchangePercent7d\x12\x1d\n" +
	"\n" +
	"change_30d\x18\a \x01(\x01R\tchange30d\x12,\n" +
	"\x12change_percent_30d\x18\b \x01(\x01R\x10changePercent30d\x12?\n" +
	"\rcalculated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\"\xe3\x01\n" +
	"\x19GetNetWorthHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"h\n" +
	"\x17NetWorthHistoryResponse\x121\n" +
	"\ahistory\x18\x01 \x03(\v2\x17.insights.NetWorthPointR\ahistory\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"U\n" +
	"\rNetWorthPoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"o\n" +
	"\x14GetAllocationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\tR\agroupBy\"\x8d\x01\n" +
	"\x12AllocationResponse\x12:\n" +
	"\vallocations\x18\x01 \x03(\v2\x18.insights.AllocationItemR\vallocations\x12\x1f\n" +
	"\vtotal_value\x18\x02 \x01(\x01R\n" +
	"totalValue\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"\x8c\x01\n" +
	"\x0eAllocationItem\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\"\xe2\x01\n" +
	"\x18GetBalanceChangesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xbc\x01\n" +
	"\x16BalanceChangesResponse\x121\n" +
	"\achanges\x18\x01 \x03(\v2\x17.insights.BalanceChangeR\achanges\x12!\n" +
	"\ftotal_change\x18\x02 \x01(\x01R\vtotalChange\x120\n" +
	"\x14total_change_percent\x18\x03 \x01(\x01R\x12totalChangePercent\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\"\xe2\x01\n" +
	"\rBalanceChange\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12)\n" +
	"\x10starting_balance\x18\x03 \x01(\x01R\x0fstartingBalance\x12%\n" +
	"\x0eending_balance\x18\x04 \x01(\x01R\rendingBalance\x12\x16\n" +
	"\x06change\x18\x05 \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\x06 \x01(\x01R\rchangePercent\"\x80\x01\n" +
	"\x10GetTrendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x12\x16\n" +
	"\x06metric\x18\x04 \x01(\tR\x06metric\"\xd1\x01\n" +
	"\x0eTrendsResponse\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.insights.TrendPointR\x04data\x12\x18\n" +
	"\aaverage\x18\x04 \x01(\x01R\aaverage\x12\x10\n" +
	"\x03min\x18\x05 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x06 \x01(\x01R\x03max\x12'\n" +
	"\x0ftrend_direction\x18\a \x01(\tR\x0etrendDirection\"h\n" +
	"\n" +
	"TrendPoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"Z\n" +
	"\x1aGetDashboardSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\"\xc3\x05\n" +
	"\x18DashboardSummaryResponse\x12\x1b\n" +
	"\tnet_worth\x18\x01 \x01(\x01R\bnetWorth\x12/\n" +
	"\x14net_worth_change_24h\x18\x02 \x01(\x01R\x11netWorthChange24h\x12>\n" +
	"\x1cnet_worth_change_percent_24h\x18\x03 \x01(\x01R\x18netWorthChangePercent24h\x12!\n" +
	"\ftotal_assets\x18\x04 \x01(\x01R\vtotalAssets\x12+\n" +
	"\x11total_liabilities\x18\x05 \x01(\x01R\x10totalLiabilities\x12%\n" +
	"\x0emonthly_income\x18\x06 \x01(\x01R\rmonthlyIncome\x12)\n" +
	"\x10monthly_expenses\x18\a \x01(\x01R\x0fmonthlyExpenses\x12'\n" +
	"\x0fmonthly_savings\x18\b \x01(\x01R\x0emonthlySavings\x12!\n" +
	"\fsavings_rate\x18\t \x01(\x01R\vsavingsRate\x12A\n" +
	"\x0ftop_allocations\x18\n" +
	" \x03(\v2\x18.insights.AllocationItemR\x0etopAllocations\x12L\n" +
	"\x13recent_transactions\x18\v \x03(\v2\x1b.insights.RecentTransactionR\x12recentTransactions\x12=\n" +
	"\x0etop_performers\x18\f \x03(\v2\x16.insights.TopPerformerR\rtopPerformers\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12?\n" +
	"\rcalculated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\"\xc5\x01\n" +
	"\x11RecentTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12.\n" +
	"\x04date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\"\x8f\x01\n" +
	"\fTopPerformer\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x16\n" +
	"\x06change\x18\x04 \x01(\x01R\x06change\x12%\n" +
	"\x0echange_percent\x18\x05 \x01(\x01R\rchangePercent\"\xdc\x01\n" +
	"\x12GetCashFlowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x12\x16\n" +
	"\x06period\x18\x03 \x01(\tR\x06period\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xd0\x01\n" +
	"\x10CashFlowResponse\x122\n" +
	"\aperiods\x18\x01 \x03(\v2\x18.insights.CashFlowPeriodR\aperiods\x12!\n" +
	"\ftotal_income\x18\x02 \x01(\x01R\vtotalIncome\x12%\n" +
	"\x0etotal_expenses\x18\x03 \x01(\x01R\rtotalExpenses\x12\"\n" +
	"\rnet_cash_flow\x18\x04 \x01(\x01R\vnetCashFlow\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\"\xde\x01\n" +
	"\x0eCashFlowPeriod\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x16\n" +
	"\x06income\x18\x04 \x01(\x01R\x06income\x12\x1a\n" +
	"\bexpenses\x18\x05 \x01(\x01R\bexpenses\x12\x10\n" +
	"\x03net\x18\x06 \x01(\x01R\x03net\"U\n" +
	"\x15CreateSnapshotRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\"\xb6\x01\n" +
	"\x13GetSnapshotsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"start_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"H\n" +
	"\x14GetSnapshotsResponse\x120\n" +
	"\tsnapshots\x18\x01 \x03(\v2\x12.insights.SnapshotR\tsnapshots2\xe5\x05\n" +
	"\x0fInsightsService\x12G\n" +
	"\vGetNetWorth\x12\x1c.insights.GetNetWorthRequest\x1a\x1a.insights.NetWorthResponse\x12\\\n" +
	"\x12GetNetWorthHistory\x12#.insights.GetNetWorthHistoryRequest\x1a!.insights.NetWorthHistoryResponse\x12M\n" +
	"\rGetAllocation\x12\x1e.insights.GetAllocationRequest\x1a\x1c.insights.AllocationResponse\x12Y\n" +
	"\x11GetBalanceChanges\x12\".insights.GetBalanceChangesRequest\x1a .insights.BalanceChangesResponse\x12A\n" +
	"\tGetTrends\x12\x1a.insights.GetTrendsRequest\x1a\x18.insights.TrendsResponse\x12_\n" +
	"\x13GetDashboardSummary\x12$.insights.GetDashboardSummaryRequest\x1a\".insights.DashboardSummaryResponse\x12G\n" +
	"\vGetCashFlow\x12\x1c.insights.GetCashFlowRequest\x1a\x1a.insights.CashFlowResponse\x12E\n" +
	"\x0eCreateSnapshot\x12\x1f.insights.CreateSnapshotRequest\x1a\x12.insights.Snapshot\x12M\n" +
	"\fGetSnapshots\x12\x1d.insights.GetSnapshotsRequest\x1a\x1e.insights.GetSnapshotsResponseB;Z9github.com/radmickey/money-control/backend/proto/insightsb\x06proto3"

var (
	file_proto_insights_proto_rawDescOnce sync.Once
	file_proto_insights_proto_rawDescData []byte
)

func file_proto_insights_proto_rawDescGZIP() []byte {
	file_proto_insights_proto_rawDescOnce.Do(func() {
		file_proto_insights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_insights_proto_rawDesc), len(file_proto_insights_proto_rawDesc)))
	})
	return file_proto_insights_proto_rawDescData
}

var file_proto_insights_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_insights_proto_goTypes = []any{
	(*Snapshot)(nil),                   // 0: insights.Snapshot
	(*GetNetWorthRequest)(nil),         // 1: insights.GetNetWorthRequest
	(*NetWorthResponse)(nil),           // 2: insights.NetWorthResponse
	(*GetNetWorthHistoryRequest)(nil),  // 3: insights.GetNetWorthHistoryRequest
	(*NetWorthHistoryResponse)(nil),    // 4: insights.NetWorthHistoryResponse
	(*NetWorthPoint)(nil),              // 5: insights.NetWorthPoint
	(*GetAllocationRequest)(nil),       // 6: insights.GetAllocationRequest
	(*AllocationResponse)(nil),         // 7: insights.AllocationResponse
	(*AllocationItem)(nil),             // 8: insights.AllocationItem
	(*GetBalanceChangesRequest)(nil),   // 9: insights.GetBalanceChangesRequest
	(*BalanceChangesResponse)(nil),     // 10: insights.BalanceChangesResponse
	(*BalanceChange)(nil),              // 11: insights.BalanceChange
	(*GetTrendsRequest)(nil),           // 12: insights.GetTrendsRequest
	(*TrendsResponse)(nil),             // 13: insights.TrendsResponse
	(*TrendPoint)(nil),                 // 14: insights.TrendPoint
	(*GetDashboardSummaryRequest)(nil), // 15: insights.GetDashboardSummaryRequest
	(*DashboardSummaryResponse)(nil),   // 16: insights.DashboardSummaryResponse
	(*RecentTransaction)(nil),          // 17: insights.RecentTransaction
	(*TopPerformer)(nil),               // 18: insights.TopPerformer
	(*GetCashFlowRequest)(nil),         // 19: insights.GetCashFlowRequest
	(*CashFlowResponse)(nil),           // 20: insights.CashFlowResponse
	(*CashFlowPeriod)(nil),             // 21: insights.CashFlowPeriod
	(*CreateSnapshotRequest)(nil),      // 22: insights.CreateSnapshotRequest
	(*GetSnapshotsRequest)(nil),        // 23: insights.GetSnapshotsRequest
	(*GetSnapshotsResponse)(nil),       // 24: insights.GetSnapshotsResponse
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
}
var file_proto_insights_proto_depIdxs = []int32{
	25, // 0: insights.Snapshot.date:type_name -> google.protobuf.Timestamp
	25, // 1: insights.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	25, // 2: insights.NetWorthResponse.calculated_at:type_name -> google.protobuf.Timestamp
	25, // 3: insights.GetNetWorthHistoryRequest.start_date:type_name -> google.protobuf.Timestamp
	25, // 4: insights.GetNetWorthHistoryRequest.end_date:type_name -> google.protobuf.Timestamp
	5,  // 5: insights.NetWorthHistoryResponse.history:type_name -> insights.NetWorthPoint
	25, // 6: insights.NetWorthPoint.date:type_name -> google.protobuf.Timestamp
	8,  // 7: insights.AllocationResponse.allocations:type_name -> insights.AllocationItem
	25, // 8: insights.GetBalanceChangesRequest.start_date:type_name -> google.protobuf.Timestamp
	25, // 9: insights.GetBalanceChangesRequest.end_date:type_name -> google.protobuf.Timestamp
	11, // 10: insights.BalanceChangesResponse.changes:type_name -> insights.BalanceChange
	14, // 11: insights.TrendsResponse.data:type_name -> insights.TrendPoint
	25, // 12: insights.TrendPoint.date:type_name -> google.protobuf.Timestamp
	8,  // 13: insights.DashboardSummaryResponse.top_allocations:type_name -> insights.AllocationItem
	17, // 14: insights.DashboardSummaryResponse.recent_transactions:type_name -> insights.RecentTransaction
	18, // 15: insights.DashboardSummaryResponse.top_performers:type_name -> insights.TopPerformer
	25, // 16: insights.DashboardSummaryResponse.calculated_at:type_name -> google.protobuf.Timestamp
	25, // 17: insights.RecentTransaction.date:type_name -> google.protobuf.Timestamp
	25, // 18: insights.GetCashFlowRequest.start_date:type_name -> google.protobuf.Timestamp
	25, // 19: insights.GetCashFlowRequest.end_date:type_name -> google.protobuf.Timestamp
	21, // 20: insights.CashFlowResponse.periods:type_name -> insights.CashFlowPeriod
	25, // 21: insights.CashFlowPeriod.start_date:type_name -> google.protobuf.Timestamp
	25, // 22: insights.CashFlowPeriod.end_date:type_name -> google.protobuf.Timestamp
	25, // 23: insights.GetSnapshotsRequest.start_date:type_name -> google.protobuf.Timestamp
	25, // 24: insights.GetSnapshotsRequest.end_date:type_name -> google.protobuf.Timestamp
	0,  // 25: insights.GetSnapshotsResponse.snapshots:type_name -> insights.Snapshot
	1,  // 26: insights.InsightsService.GetNetWorth:input_type -> insights.GetNetWorthRequest
	3,  // 27: insights.InsightsService.GetNetWorthHistory:input_type -> insights.GetNetWorthHistoryRequest
	6,  // 28: insights.InsightsService.GetAllocation:input_type -> insights.GetAllocationRequest
	9,  // 29: insights.InsightsService.GetBalanceChanges:input_type -> insights.GetBalanceChangesRequest
	12, // 30: insights.InsightsService.GetTrends:input_type -> insights.GetTrendsRequest
	15, // 31: insights.InsightsService.GetDashboardSummary:input_type -> insights.GetDashboardSummaryRequest
	19, // 32: insights.InsightsService.GetCashFlow:input_type -> insights.GetCashFlowRequest
	22, // 33: insights.InsightsService.CreateSnapshot:input_type -> insights.CreateSnapshotRequest
	23, // 34: insights.InsightsService.GetSnapshots:input_type -> insights.GetSnapshotsRequest
	2,  // 35: insights.InsightsService.GetNetWorth:output_type -> insights.NetWorthResponse
	4,  // 36: insights.InsightsService.GetNetWorthHistory:output_type -> insights.NetWorthHistoryResponse
	7,  // 37: insights.InsightsService.GetAllocation:output_type -> insights.AllocationResponse
	10, // 38: insights.InsightsService.GetBalanceChanges:output_type -> insights.BalanceChangesResponse
	13, // 39: insights.InsightsService.GetTrends:output_type -> insights.TrendsResponse
	16, // 40: insights.InsightsService.GetDashboardSummary:output_type -> insights.DashboardSummaryResponse
	20, // 41: insights.InsightsService.GetCashFlow:output_type -> insights.CashFlowResponse
	0,  // 42: insights.InsightsService.CreateSnapshot:output_type -> insights.Snapshot
	24, // 43: insights.InsightsService.GetSnapshots:output_type -> insights.GetSnapshotsResponse
	35, // [35:44] is the sub-list for method output_type
	26, // [26:35] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_proto_insights_proto_init() }
func file_proto_insights_proto_init() {
	if File_proto_insights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_insights_proto_rawDesc), len(file_proto_insights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_insights_proto_goTypes,
		DependencyIndexes: file_proto_insights_proto_depIdxs,
		MessageInfos:      file_proto_insights_proto_msgTypes,
	}.Build()
	File_proto_insights_proto = out.File
	file_proto_insights_proto_goTypes = nil
	file_proto_insights_proto_depIdxs = nil
}
