// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/insights.proto

package insights

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InsightsService_GetNetWorth_FullMethodName         = "/insights.InsightsService/GetNetWorth"
	InsightsService_GetNetWorthHistory_FullMethodName  = "/insights.InsightsService/GetNetWorthHistory"
	InsightsService_GetAllocation_FullMethodName       = "/insights.InsightsService/GetAllocation"
	InsightsService_GetBalanceChanges_FullMethodName   = "/insights.InsightsService/GetBalanceChanges"
	InsightsService_GetTrends_FullMethodName           = "/insights.InsightsService/GetTrends"
	InsightsService_GetDashboardSummary_FullMethodName = "/insights.InsightsService/GetDashboardSummary"
	InsightsService_GetCashFlow_FullMethodName         = "/insights.InsightsService/GetCashFlow"
	InsightsService_CreateSnapshot_FullMethodName      = "/insights.InsightsService/CreateSnapshot"
	InsightsService_GetSnapshots_FullMethodName        = "/insights.InsightsService/GetSnapshots"
)

// InsightsServiceClient is the client API for InsightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InsightsServiceClient interface {
	GetNetWorth(ctx context.Context, in *GetNetWorthRequest, opts ...grpc.CallOption) (*NetWorthResponse, error)
	GetNetWorthHistory(ctx context.Context, in *GetNetWorthHistoryRequest, opts ...grpc.CallOption) (*NetWorthHistoryResponse, error)
	GetAllocation(ctx context.Context, in *GetAllocationRequest, opts ...grpc.CallOption) (*AllocationResponse, error)
	GetBalanceChanges(ctx context.Context, in *GetBalanceChangesRequest, opts ...grpc.CallOption) (*BalanceChangesResponse, error)
	GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*TrendsResponse, error)
	GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...grpc.CallOption) (*DashboardSummaryResponse, error)
	GetCashFlow(ctx context.Context, in *GetCashFlowRequest, opts ...grpc.CallOption) (*CashFlowResponse, error)
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	GetSnapshots(ctx context.Context, in *GetSnapshotsRequest, opts ...grpc.CallOption) (*GetSnapshotsResponse, error)
}

type insightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInsightsServiceClient(cc grpc.ClientConnInterface) InsightsServiceClient {
	return &insightsServiceClient{cc}
}

func (c *insightsServiceClient) GetNetWorth(ctx context.Context, in *GetNetWorthRequest, opts ...grpc.CallOption) (*NetWorthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetWorthResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetNetWorth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetNetWorthHistory(ctx context.Context, in *GetNetWorthHistoryRequest, opts ...grpc.CallOption) (*NetWorthHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NetWorthHistoryResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetNetWorthHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetAllocation(ctx context.Context, in *GetAllocationRequest, opts ...grpc.CallOption) (*AllocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocationResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetAllocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetBalanceChanges(ctx context.Context, in *GetBalanceChangesRequest, opts ...grpc.CallOption) (*BalanceChangesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceChangesResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetBalanceChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*TrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrendsResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetDashboardSummary(ctx context.Context, in *GetDashboardSummaryRequest, opts ...grpc.CallOption) (*DashboardSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardSummaryResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetDashboardSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetCashFlow(ctx context.Context, in *GetCashFlowRequest, opts ...grpc.CallOption) (*CashFlowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CashFlowResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetCashFlow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, InsightsService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *insightsServiceClient) GetSnapshots(ctx context.Context, in *GetSnapshotsRequest, opts ...grpc.CallOption) (*GetSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotsResponse)
	err := c.cc.Invoke(ctx, InsightsService_GetSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InsightsServiceServer is the server API for InsightsService service.
// All implementations must embed UnimplementedInsightsServiceServer
// for forward compatibility.
type InsightsServiceServer interface {
	GetNetWorth(context.Context, *GetNetWorthRequest) (*NetWorthResponse, error)
	GetNetWorthHistory(context.Context, *GetNetWorthHistoryRequest) (*NetWorthHistoryResponse, error)
	GetAllocation(context.Context, *GetAllocationRequest) (*AllocationResponse, error)
	GetBalanceChanges(context.Context, *GetBalanceChangesRequest) (*BalanceChangesResponse, error)
	GetTrends(context.Context, *GetTrendsRequest) (*TrendsResponse, error)
	GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*DashboardSummaryResponse, error)
	GetCashFlow(context.Context, *GetCashFlowRequest) (*CashFlowResponse, error)
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*Snapshot, error)
	GetSnapshots(context.Context, *GetSnapshotsRequest) (*GetSnapshotsResponse, error)
	mustEmbedUnimplementedInsightsServiceServer()
}

// UnimplementedInsightsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInsightsServiceServer struct{}

func (UnimplementedInsightsServiceServer) GetNetWorth(context.Context, *GetNetWorthRequest) (*NetWorthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetWorth not implemented")
}
func (UnimplementedInsightsServiceServer) GetNetWorthHistory(context.Context, *GetNetWorthHistoryRequest) (*NetWorthHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetWorthHistory not implemented")
}
func (UnimplementedInsightsServiceServer) GetAllocation(context.Context, *GetAllocationRequest) (*AllocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllocation not implemented")
}
func (UnimplementedInsightsServiceServer) GetBalanceChanges(context.Context, *GetBalanceChangesRequest) (*BalanceChangesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceChanges not implemented")
}
func (UnimplementedInsightsServiceServer) GetTrends(context.Context, *GetTrendsRequest) (*TrendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrends not implemented")
}
func (UnimplementedInsightsServiceServer) GetDashboardSummary(context.Context, *GetDashboardSummaryRequest) (*DashboardSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardSummary not implemented")
}
func (UnimplementedInsightsServiceServer) GetCashFlow(context.Context, *GetCashFlowRequest) (*CashFlowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCashFlow not implemented")
}
func (UnimplementedInsightsServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedInsightsServiceServer) GetSnapshots(context.Context, *GetSnapshotsRequest) (*GetSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSnapshots not implemented")
}
func (UnimplementedInsightsServiceServer) mustEmbedUnimplementedInsightsServiceServer() {}
func (UnimplementedInsightsServiceServer) testEmbeddedByValue()                         {}

// UnsafeInsightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InsightsServiceServer will
// result in compilation errors.
type UnsafeInsightsServiceServer interface {
	mustEmbedUnimplementedInsightsServiceServer()
}

func RegisterInsightsServiceServer(s grpc.ServiceRegistrar, srv InsightsServiceServer) {
	// If the following call panics, it indicates UnimplementedInsightsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InsightsService_ServiceDesc, srv)
}

func _InsightsService_GetNetWorth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetWorthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetNetWorth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetNetWorth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetNetWorth(ctx, req.(*GetNetWorthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetNetWorthHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetWorthHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetNetWorthHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetNetWorthHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetNetWorthHistory(ctx, req.(*GetNetWorthHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetAllocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetAllocation(ctx, req.(*GetAllocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetBalanceChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetBalanceChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetBalanceChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetBalanceChanges(ctx, req.(*GetBalanceChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetTrends(ctx, req.(*GetTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetDashboardSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetDashboardSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetDashboardSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetDashboardSummary(ctx, req.(*GetDashboardSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetCashFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCashFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetCashFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetCashFlow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetCashFlow(ctx, req.(*GetCashFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InsightsService_GetSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InsightsServiceServer).GetSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InsightsService_GetSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InsightsServiceServer).GetSnapshots(ctx, req.(*GetSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InsightsService_ServiceDesc is the grpc.ServiceDesc for InsightsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InsightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "insights.InsightsService",
	HandlerType: (*InsightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetWorth",
			Handler:    _InsightsService_GetNetWorth_Handler,
		},
		{
			MethodName: "GetNetWorthHistory",
			Handler:    _InsightsService_GetNetWorthHistory_Handler,
		},
		{
			MethodName: "GetAllocation",
			Handler:    _InsightsService_GetAllocation_Handler,
		},
		{
			MethodName: "GetBalanceChanges",
			Handler:    _InsightsService_GetBalanceChanges_Handler,
		},
		{
			MethodName: "GetTrends",
			Handler:    _InsightsService_GetTrends_Handler,
		},
		{
			MethodName: "GetDashboardSummary",
			Handler:    _InsightsService_GetDashboardSummary_Handler,
		},
		{
			MethodName: "GetCashFlow",
			Handler:    _InsightsService_GetCashFlow_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _InsightsService_CreateSnapshot_Handler,
		},
		{
			MethodName: "GetSnapshots",
			Handler:    _InsightsService_GetSnapshots_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/insights.proto",
}
