// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/accounts.proto

package accounts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_BANK        AccountType = 1
	AccountType_ACCOUNT_TYPE_CASH        AccountType = 2
	AccountType_ACCOUNT_TYPE_INVESTMENT  AccountType = 3
	AccountType_ACCOUNT_TYPE_CRYPTO      AccountType = 4
	AccountType_ACCOUNT_TYPE_REAL_ESTATE AccountType = 5
	AccountType_ACCOUNT_TYPE_OTHER       AccountType = 6
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_BANK",
		2: "ACCOUNT_TYPE_CASH",
		3: "ACCOUNT_TYPE_INVESTMENT",
		4: "ACCOUNT_TYPE_CRYPTO",
		5: "ACCOUNT_TYPE_REAL_ESTATE",
		6: "ACCOUNT_TYPE_OTHER",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_BANK":        1,
		"ACCOUNT_TYPE_CASH":        2,
		"ACCOUNT_TYPE_INVESTMENT":  3,
		"ACCOUNT_TYPE_CRYPTO":      4,
		"ACCOUNT_TYPE_REAL_ESTATE": 5,
		"ACCOUNT_TYPE_OTHER":       6,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounts_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_accounts_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{0}
}

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_BANK        AssetType = 1
	AssetType_ASSET_TYPE_CASH        AssetType = 2
	AssetType_ASSET_TYPE_STOCKS      AssetType = 3
	AssetType_ASSET_TYPE_CRYPTO      AssetType = 4
	AssetType_ASSET_TYPE_ETF         AssetType = 5
	AssetType_ASSET_TYPE_REAL_ESTATE AssetType = 6
	AssetType_ASSET_TYPE_BONDS       AssetType = 7
	AssetType_ASSET_TYPE_OTHER       AssetType = 8
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_BANK",
		2: "ASSET_TYPE_CASH",
		3: "ASSET_TYPE_STOCKS",
		4: "ASSET_TYPE_CRYPTO",
		5: "ASSET_TYPE_ETF",
		6: "ASSET_TYPE_REAL_ESTATE",
		7: "ASSET_TYPE_BONDS",
		8: "ASSET_TYPE_OTHER",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_BANK":        1,
		"ASSET_TYPE_CASH":        2,
		"ASSET_TYPE_STOCKS":      3,
		"ASSET_TYPE_CRYPTO":      4,
		"ASSET_TYPE_ETF":         5,
		"ASSET_TYPE_REAL_ESTATE": 6,
		"ASSET_TYPE_BONDS":       7,
		"ASSET_TYPE_OTHER":       8,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_accounts_proto_enumTypes[1].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_proto_accounts_proto_enumTypes[1]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{1}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          AccountType            `protobuf:"varint,4,opt,name=type,proto3,enum=accounts.AccountType" json:"type,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,6,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SubAccounts   []*SubAccount          `protobuf:"bytes,11,rep,name=sub_accounts,json=subAccounts,proto3" json:"sub_accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *Account) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Account) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Account) GetSubAccounts() []*SubAccount {
	if x != nil {
		return x.SubAccounts
	}
	return nil
}

type SubAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AssetType     AssetType              `protobuf:"varint,4,opt,name=asset_type,json=assetType,proto3,enum=accounts.AssetType" json:"asset_type,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Symbol        string                 `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubAccount) Reset() {
	*x = SubAccount{}
	mi := &file_proto_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubAccount) ProtoMessage() {}

func (x *SubAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubAccount.ProtoReflect.Descriptor instead.
func (*SubAccount) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *SubAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SubAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubAccount) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *SubAccount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SubAccount) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *SubAccount) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SubAccount) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *SubAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SubAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SubAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AccountType            `protobuf:"varint,3,opt,name=type,proto3,enum=accounts.AccountType" json:"type,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAccountRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          AccountType            `protobuf:"varint,2,opt,name=type,proto3,enum=accounts.AccountType" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_proto_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAccountsRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *ListAccountsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*Account             `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_proto_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *ListAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAccountsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAccountsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,5,opt,name=icon,proto3" json:"icon,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAccountRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *UpdateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CreateSubAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	AssetType     AssetType              `protobuf:"varint,4,opt,name=asset_type,json=assetType,proto3,enum=accounts.AssetType" json:"asset_type,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Balance       float64                `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	Symbol        string                 `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      float64                `protobuf:"fixed64,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSubAccountRequest) Reset() {
	*x = CreateSubAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSubAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSubAccountRequest) ProtoMessage() {}

func (x *CreateSubAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSubAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateSubAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *CreateSubAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CreateSubAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateSubAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSubAccountRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *CreateSubAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateSubAccountRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *CreateSubAccountRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateSubAccountRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateSubAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetSubAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubAccountRequest) Reset() {
	*x = GetSubAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubAccountRequest) ProtoMessage() {}

func (x *GetSubAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubAccountRequest.ProtoReflect.Descriptor instead.
func (*GetSubAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *GetSubAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetSubAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListSubAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetType     AssetType              `protobuf:"varint,3,opt,name=asset_type,json=assetType,proto3,enum=accounts.AssetType" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubAccountsRequest) Reset() {
	*x = ListSubAccountsRequest{}
	mi := &file_proto_accounts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubAccountsRequest) ProtoMessage() {}

func (x *ListSubAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListSubAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{10}
}

func (x *ListSubAccountsRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ListSubAccountsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListSubAccountsRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

type ListSubAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubAccounts   []*SubAccount          `protobuf:"bytes,1,rep,name=sub_accounts,json=subAccounts,proto3" json:"sub_accounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubAccountsResponse) Reset() {
	*x = ListSubAccountsResponse{}
	mi := &file_proto_accounts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubAccountsResponse) ProtoMessage() {}

func (x *ListSubAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListSubAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{11}
}

func (x *ListSubAccountsResponse) GetSubAccounts() []*SubAccount {
	if x != nil {
		return x.SubAccounts
	}
	return nil
}

type UpdateSubAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Balance       float64                `protobuf:"fixed64,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubAccountRequest) Reset() {
	*x = UpdateSubAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubAccountRequest) ProtoMessage() {}

func (x *UpdateSubAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSubAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSubAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSubAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSubAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateSubAccountRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UpdateSubAccountRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeleteSubAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSubAccountRequest) Reset() {
	*x = DeleteSubAccountRequest{}
	mi := &file_proto_accounts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSubAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSubAccountRequest) ProtoMessage() {}

func (x *DeleteSubAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSubAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteSubAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSubAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteSubAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateSubAccountBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Quantity      float64                `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubAccountBalanceRequest) Reset() {
	*x = UpdateSubAccountBalanceRequest{}
	mi := &file_proto_accounts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubAccountBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubAccountBalanceRequest) ProtoMessage() {}

func (x *UpdateSubAccountBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubAccountBalanceRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubAccountBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateSubAccountBalanceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSubAccountBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSubAccountBalanceRequest) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UpdateSubAccountBalanceRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetUserNetWorthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserNetWorthRequest) Reset() {
	*x = GetUserNetWorthRequest{}
	mi := &file_proto_accounts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserNetWorthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserNetWorthRequest) ProtoMessage() {}

func (x *GetUserNetWorthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserNetWorthRequest.ProtoReflect.Descriptor instead.
func (*GetUserNetWorthRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserNetWorthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserNetWorthRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type NetWorthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalNetWorth float64                `protobuf:"fixed64,1,opt,name=total_net_worth,json=totalNetWorth,proto3" json:"total_net_worth,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	ByAccountType map[string]float64     `protobuf:"bytes,3,rep,name=by_account_type,json=byAccountType,proto3" json:"by_account_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	ByAssetType   map[string]float64     `protobuf:"bytes,4,rep,name=by_asset_type,json=byAssetType,proto3" json:"by_asset_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	CalculatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetWorthResponse) Reset() {
	*x = NetWorthResponse{}
	mi := &file_proto_accounts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetWorthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetWorthResponse) ProtoMessage() {}

func (x *NetWorthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetWorthResponse.ProtoReflect.Descriptor instead.
func (*NetWorthResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{16}
}

func (x *NetWorthResponse) GetTotalNetWorth() float64 {
	if x != nil {
		return x.TotalNetWorth
	}
	return 0
}

func (x *NetWorthResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *NetWorthResponse) GetByAccountType() map[string]float64 {
	if x != nil {
		return x.ByAccountType
	}
	return nil
}

func (x *NetWorthResponse) GetByAssetType() map[string]float64 {
	if x != nil {
		return x.ByAssetType
	}
	return nil
}

func (x *NetWorthResponse) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

type GetAccountsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsSummaryRequest) Reset() {
	*x = GetAccountsSummaryRequest{}
	mi := &file_proto_accounts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsSummaryRequest) ProtoMessage() {}

func (x *GetAccountsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{17}
}

func (x *GetAccountsSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccountsSummaryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalAccounts    int32                  `protobuf:"varint,1,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	TotalSubAccounts int32                  `protobuf:"varint,2,opt,name=total_sub_accounts,json=totalSubAccounts,proto3" json:"total_sub_accounts,omitempty"`
	ByType           []*AccountTypeSummary  `protobuf:"bytes,3,rep,name=by_type,json=byType,proto3" json:"by_type,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountsSummaryResponse) Reset() {
	*x = AccountsSummaryResponse{}
	mi := &file_proto_accounts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsSummaryResponse) ProtoMessage() {}

func (x *AccountsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsSummaryResponse.ProtoReflect.Descriptor instead.
func (*AccountsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{18}
}

func (x *AccountsSummaryResponse) GetTotalAccounts() int32 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *AccountsSummaryResponse) GetTotalSubAccounts() int32 {
	if x != nil {
		return x.TotalSubAccounts
	}
	return 0
}

func (x *AccountsSummaryResponse) GetByType() []*AccountTypeSummary {
	if x != nil {
		return x.ByType
	}
	return nil
}

type AccountTypeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AccountType            `protobuf:"varint,1,opt,name=type,proto3,enum=accounts.AccountType" json:"type,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,3,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTypeSummary) Reset() {
	*x = AccountTypeSummary{}
	mi := &file_proto_accounts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTypeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTypeSummary) ProtoMessage() {}

func (x *AccountTypeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTypeSummary.ProtoReflect.Descriptor instead.
func (*AccountTypeSummary) Descriptor() ([]byte, []int) {
	return file_proto_accounts_proto_rawDescGZIP(), []int{19}
}

func (x *AccountTypeSummary) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *AccountTypeSummary) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AccountTypeSummary) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *AccountTypeSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_accounts_proto protoreflect.FileDescriptor

const file_proto_accounts_proto_rawDesc = "" +
	"\n" +
	"\x14proto/accounts.proto\x12\baccounts\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x03\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.accounts.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12#\n" +
	"\rtotal_balance\x18\x06 \x01(\x01R\ftotalBalance\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\fsub_accounts\x18\v \x03(\v2\x14.accounts.SubAccountR\vsubAccounts\"\x85\x03\n" +
	"\n" +
	"SubAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\x0e2\x13.accounts.AssetTypeR\tassetType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12\x16\n" +
	"\x06symbol\x18\a \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x01R\bquantity\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc0\x01\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.accounts.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x06 \x01(\tR\x04icon\"<\n" +
	"\x11GetAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8a\x01\n" +
	"\x13ListAccountsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.accounts.AccountTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x8c\x01\n" +
	"\x14ListAccountsResponse\x12-\n" +
	"\baccounts\x18\x01 \x03(\v2\x11.accounts.AccountR\baccounts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xa5\x01\n" +
	"\x14UpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\tR\x04icon\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"?\n" +
	"\x14DeleteAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa5\x02\n" +
	"\x17CreateSubAccountRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x122\n" +
	"\n" +
	"asset_type\x18\x04 \x01(\x0e2\x13.accounts.AssetTypeR\tassetType\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x01R\abalance\x12\x16\n" +
	"\x06symbol\x18\a \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x01R\bquantity\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"?\n" +
	"\x14GetSubAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x84\x01\n" +
	"\x16ListSubAccountsRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x122\n" +
	"\n" +
	"asset_type\x18\x03 \x01(\x0e2\x13.accounts.AssetTypeR\tassetType\"R\n" +
	"\x17ListSubAccountsResponse\x127\n" +
	"\fsub_accounts\x18\x01 \x03(\v2\x14.accounts.SubAccountR\vsubAccounts\"\xae\x01\n" +
	"\x17UpdateSubAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x18\n" +
	"\abalance\x18\x05 \x01(\x01R\abalance\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\"B\n" +
	"\x17DeleteSubAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x7f\n" +
	"\x1eUpdateSubAccountBalanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x01R\abalance\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x01R\bquantity\"V\n" +
	"\x16GetUserNetWorthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\"\xc1\x03\n" +
	"\x10NetWorthResponse\x12&\n" +
	"\x0ftotal_net_worth\x18\x01 \x01(\x01R\rtotalNetWorth\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x12U\n" +
	"\x0fby_account_type\x18\x03 \x03(\v2-.accounts.NetWorthResponse.ByAccountTypeEntryR\rbyAccountType\x12O\n" +
	"\rby_asset_type\x18\x04 \x03(\v2+.accounts.NetWorthResponse.ByAssetTypeEntryR\vbyAssetType\x12?\n" +
	"\rcalculated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\x1a@\n" +
	"\x12ByAccountTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a>\n" +
	"\x10ByAssetTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"4\n" +
	"\x19GetAccountsSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa5\x01\n" +
	"\x17AccountsSummaryResponse\x12%\n" +
	"\x0etotal_accounts\x18\x01 \x01(\x05R\rtotalAccounts\x12,\n" +
	"\x12total_sub_accounts\x18\x02 \x01(\x05R\x10totalSubAccounts\x125\n" +
	"\aby_type\x18\x03 \x03(\v2\x1c.accounts.AccountTypeSummaryR\x06byType\"\x96\x01\n" +
	"\x12AccountTypeSummary\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.accounts.AccountTypeR\x04type\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12#\n" +
	"\rtotal_balance\x18\x03 \x01(\x01R\ftotalBalance\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency*\xc5\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_TYPE_BANK\x10\x01\x12\x15\n" +
	"\x11ACCOUNT_TYPE_CASH\x10\x02\x12\x1b\n" +
	"\x17ACCOUNT_TYPE_INVESTMENT\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_CRYPTO\x10\x04\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_REAL_ESTATE\x10\x05\x12\x16\n" +
	"\x12ACCOUNT_TYPE_OTHER\x10\x06*\xdb\x01\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fASSET_TYPE_BANK\x10\x01\x12\x13\n" +
	"\x0fASSET_TYPE_CASH\x10\x02\x12\x15\n" +
	"\x11ASSET_TYPE_STOCKS\x10\x03\x12\x15\n" +
	"\x11ASSET_TYPE_CRYPTO\x10\x04\x12\x12\n" +
	"\x0eASSET_TYPE_ETF\x10\x05\x12\x1a\n" +
	"\x16ASSET_TYPE_REAL_ESTATE\x10\x06\x12\x14\n" +
	"\x10ASSET_TYPE_BONDS\x10\a\x12\x14\n" +
	"\x10ASSET_TYPE_OTHER\x10\b2\x81\b\n" +
	"\x0fAccountsService\x12B\n" +
	"\rCreateAccount\x12\x1e.accounts.CreateAccountRequest\x1a\x11.accounts.Account\x12<\n" +
	"\n" +
	"GetAccount\x12\x1b.accounts.GetAccountRequest\x1a\x11.accounts.Account\x12M\n" +
	"\fListAccounts\x12\x1d.accounts.ListAccountsRequest\x1a\x1e.accounts.ListAccountsResponse\x12B\n" +
	"\rUpdateAccount\x12\x1e.accounts.UpdateAccountRequest\x1a\x11.accounts.Account\x12G\n" +
	"\rDeleteAccount\x12\x1e.accounts.DeleteAccountRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\x10CreateSubAccount\x12!.accounts.CreateSubAccountRequest\x1a\x14.accounts.SubAccount\x12E\n" +
	"\rGetSubAccount\x12\x1e.accounts.GetSubAccountRequest\x1a\x14.accounts.SubAccount\x12V\n" +
	"\x0fListSubAccounts\x12 .accounts.ListSubAccountsRequest\x1a!.accounts.ListSubAccountsResponse\x12K\n" +
	"\x10UpdateSubAccount\x12!.accounts.UpdateSubAccountRequest\x1a\x14.accounts.SubAccount\x12M\n" +
	"\x10DeleteSubAccount\x12!.accounts.DeleteSubAccountRequest\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\x17UpdateSubAccountBalance\x12(.accounts.UpdateSubAccountBalanceRequest\x1a\x14.accounts.SubAccount\x12O\n" +
	"\x0fGetUserNetWorth\x12 .accounts.GetUserNetWorthRequest\x1a\x1a.accounts.NetWorthResponse\x12\\\n" +
	"\x12GetAccountsSummary\x12#.accounts.GetAccountsSummaryRequest\x1a!.accounts.AccountsSummaryResponseB;Z9github.com/radmickey/money-control/backend/proto/accountsb\x06proto3"

var (
	file_proto_accounts_proto_rawDescOnce sync.Once
	file_proto_accounts_proto_rawDescData []byte
)

func file_proto_accounts_proto_rawDescGZIP() []byte {
	file_proto_accounts_proto_rawDescOnce.Do(func() {
		file_proto_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounts_proto_rawDesc), len(file_proto_accounts_proto_rawDesc)))
	})
	return file_proto_accounts_proto_rawDescData
}

var file_proto_accounts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_accounts_proto_goTypes = []any{
	(AccountType)(0),                       // 0: accounts.AccountType
	(AssetType)(0),                         // 1: accounts.AssetType
	(*Account)(nil),                        // 2: accounts.Account
	(*SubAccount)(nil),                     // 3: accounts.SubAccount
	(*CreateAccountRequest)(nil),           // 4: accounts.CreateAccountRequest
	(*GetAccountRequest)(nil),              // 5: accounts.GetAccountRequest
	(*ListAccountsRequest)(nil),            // 6: accounts.ListAccountsRequest
	(*ListAccountsResponse)(nil),           // 7: accounts.ListAccountsResponse
	(*UpdateAccountRequest)(nil),           // 8: accounts.UpdateAccountRequest
	(*DeleteAccountRequest)(nil),           // 9: accounts.DeleteAccountRequest
	(*CreateSubAccountRequest)(nil),        // 10: accounts.CreateSubAccountRequest
	(*GetSubAccountRequest)(nil),           // 11: accounts.GetSubAccountRequest
	(*ListSubAccountsRequest)(nil),         // 12: accounts.ListSubAccountsRequest
	(*ListSubAccountsResponse)(nil),        // 13: accounts.ListSubAccountsResponse
	(*UpdateSubAccountRequest)(nil),        // 14: accounts.UpdateSubAccountRequest
	(*DeleteSubAccountRequest)(nil),        // 15: accounts.DeleteSubAccountRequest
	(*UpdateSubAccountBalanceRequest)(nil), // 16: accounts.UpdateSubAccountBalanceRequest
	(*GetUserNetWorthRequest)(nil),         // 17: accounts.GetUserNetWorthRequest
	(*NetWorthResponse)(nil),               // 18: accounts.NetWorthResponse
	(*GetAccountsSummaryRequest)(nil),      // 19: accounts.GetAccountsSummaryRequest
	(*AccountsSummaryResponse)(nil),        // 20: accounts.AccountsSummaryResponse
	(*AccountTypeSummary)(nil),             // 21: accounts.AccountTypeSummary
	nil,                                    // 22: accounts.NetWorthResponse.ByAccountTypeEntry
	nil,                                    // 23: accounts.NetWorthResponse.ByAssetTypeEntry
	(*timestamppb.Timestamp)(nil),          // 24: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 25: google.protobuf.Empty
}
var file_proto_accounts_proto_depIdxs = []int32{
	0,  // 0: accounts.Account.type:type_name -> accounts.AccountType
	24, // 1: accounts.Account.created_at:type_name -> google.protobuf.Timestamp
	24, // 2: accounts.Account.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 3: accounts.Account.sub_accounts:type_name -> accounts.SubAccount
	1,  // 4: accounts.SubAccount.asset_type:type_name -> accounts.AssetType
	24, // 5: accounts.SubAccount.created_at:type_name -> google.protobuf.Timestamp
	24, // 6: accounts.SubAccount.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: accounts.CreateAccountRequest.type:type_name -> accounts.AccountType
	0,  // 8: accounts.ListAccountsRequest.type:type_name -> accounts.AccountType
	2,  // 9: accounts.ListAccountsResponse.accounts:type_name -> accounts.Account
	1,  // 10: accounts.CreateSubAccountRequest.asset_type:type_name -> accounts.AssetType
	1,  // 11: accounts.ListSubAccountsRequest.asset_type:type_name -> accounts.AssetType
	3,  // 12: accounts.ListSubAccountsResponse.sub_accounts:type_name -> accounts.SubAccount
	22, // 13: accounts.NetWorthResponse.by_account_type:type_name -> accounts.NetWorthResponse.ByAccountTypeEntry
	23, // 14: accounts.NetWorthResponse.by_asset_type:type_name -> accounts.NetWorthResponse.ByAssetTypeEntry
	24, // 15: accounts.NetWorthResponse.calculated_at:type_name -> google.protobuf.Timestamp
	21, // 16: accounts.AccountsSummaryResponse.by_type:type_name -> accounts.AccountTypeSummary
	0,  // 17: accounts.AccountTypeSummary.type:type_name -> accounts.AccountType
	4,  // 18: accounts.AccountsService.CreateAccount:input_type -> accounts.CreateAccountRequest
	5,  // 19: accounts.AccountsService.GetAccount:input_type -> accounts.GetAccountRequest
	6,  // 20: accounts.AccountsService.ListAccounts:input_type -> accounts.ListAccountsRequest
	8,  // 21: accounts.AccountsService.UpdateAccount:input_type -> accounts.UpdateAccountRequest
	9,  // 22: accounts.AccountsService.DeleteAccount:input_type -> accounts.DeleteAccountRequest
	10, // 23: accounts.AccountsService.CreateSubAccount:input_type -> accounts.CreateSubAccountRequest
	11, // 24: accounts.AccountsService.GetSubAccount:input_type -> accounts.GetSubAccountRequest
	12, // 25: accounts.AccountsService.ListSubAccounts:input_type -> accounts.ListSubAccountsRequest
	14, // 26: accounts.AccountsService.UpdateSubAccount:input_type -> accounts.UpdateSubAccountRequest
	15, // 27: accounts.AccountsService.DeleteSubAccount:input_type -> accounts.DeleteSubAccountRequest
	16, // 28: accounts.AccountsService.UpdateSubAccountBalance:input_type -> accounts.UpdateSubAccountBalanceRequest
	17, // 29: accounts.AccountsService.GetUserNetWorth:input_type -> accounts.GetUserNetWorthRequest
	19, // 30: accounts.AccountsService.GetAccountsSummary:input_type -> accounts.GetAccountsSummaryRequest
	2,  // 31: accounts.AccountsService.CreateAccount:output_type -> accounts.Account
	2,  // 32: accounts.AccountsService.GetAccount:output_type -> accounts.Account
	7,  // 33: accounts.AccountsService.ListAccounts:output_type -> accounts.ListAccountsResponse
	2,  // 34: accounts.AccountsService.UpdateAccount:output_type -> accounts.Account
	25, // 35: accounts.AccountsService.DeleteAccount:output_type -> google.protobuf.Empty
	3,  // 36: accounts.AccountsService.CreateSubAccount:output_type -> accounts.SubAccount
	3,  // 37: accounts.AccountsService.GetSubAccount:output_type -> accounts.SubAccount
	13, // 38: accounts.AccountsService.ListSubAccounts:output_type -> accounts.ListSubAccountsResponse
	3,  // 39: accounts.AccountsService.UpdateSubAccount:output_type -> accounts.SubAccount
	25, // 40: accounts.AccountsService.DeleteSubAccount:output_type -> google.protobuf.Empty
	3,  // 41: accounts.AccountsService.UpdateSubAccountBalance:output_type -> accounts.SubAccount
	18, // 42: accounts.AccountsService.GetUserNetWorth:output_type -> accounts.NetWorthResponse
	20, // 43: accounts.AccountsService.GetAccountsSummary:output_type -> accounts.AccountsSummaryResponse
	31, // [31:44] is the sub-list for method output_type
	18, // [18:31] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_accounts_proto_init() }
func file_proto_accounts_proto_init() {
	if File_proto_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounts_proto_rawDesc), len(file_proto_accounts_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_accounts_proto_goTypes,
		DependencyIndexes: file_proto_accounts_proto_depIdxs,
		EnumInfos:         file_proto_accounts_proto_enumTypes,
		MessageInfos:      file_proto_accounts_proto_msgTypes,
	}.Build()
	File_proto_accounts_proto = out.File
	file_proto_accounts_proto_goTypes = nil
	file_proto_accounts_proto_depIdxs = nil
}
