// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRate) Reset() {
	*x = ExchangeRate{}
	mi := &file_proto_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRate) ProtoMessage() {}

func (x *ExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRate.ProtoReflect.Descriptor instead.
func (*ExchangeRate) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRate) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRate) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRate) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetExchangeRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExchangeRateRequest) Reset() {
	*x = GetExchangeRateRequest{}
	mi := &file_proto_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExchangeRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExchangeRateRequest) ProtoMessage() {}

func (x *GetExchangeRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExchangeRateRequest.ProtoReflect.Descriptor instead.
func (*GetExchangeRateRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{1}
}

func (x *GetExchangeRateRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetExchangeRateRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ExchangeRateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *ExchangeRate          `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateResponse) Reset() {
	*x = ExchangeRateResponse{}
	mi := &file_proto_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateResponse) ProtoMessage() {}

func (x *ExchangeRateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateResponse.ProtoReflect.Descriptor instead.
func (*ExchangeRateResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{2}
}

func (x *ExchangeRateResponse) GetRate() *ExchangeRate {
	if x != nil {
		return x.Rate
	}
	return nil
}

type GetMultipleExchangeRatesRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency     string                 `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	TargetCurrencies []string               `protobuf:"bytes,2,rep,name=target_currencies,json=targetCurrencies,proto3" json:"target_currencies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetMultipleExchangeRatesRequest) Reset() {
	*x = GetMultipleExchangeRatesRequest{}
	mi := &file_proto_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleExchangeRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleExchangeRatesRequest) ProtoMessage() {}

func (x *GetMultipleExchangeRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleExchangeRatesRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleExchangeRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{3}
}

func (x *GetMultipleExchangeRatesRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetMultipleExchangeRatesRequest) GetTargetCurrencies() []string {
	if x != nil {
		return x.TargetCurrencies
	}
	return nil
}

type GetMultipleExchangeRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency  string                 `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	Rates         map[string]float64     `protobuf:"bytes,2,rep,name=rates,proto3" json:"rates,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleExchangeRatesResponse) Reset() {
	*x = GetMultipleExchangeRatesResponse{}
	mi := &file_proto_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleExchangeRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleExchangeRatesResponse) ProtoMessage() {}

func (x *GetMultipleExchangeRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleExchangeRatesResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleExchangeRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{4}
}

func (x *GetMultipleExchangeRatesResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetMultipleExchangeRatesResponse) GetRates() map[string]float64 {
	if x != nil {
		return x.Rates
	}
	return nil
}

func (x *GetMultipleExchangeRatesResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ConvertAmountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FromCurrency  string                 `protobuf:"bytes,2,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,3,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertAmountRequest) Reset() {
	*x = ConvertAmountRequest{}
	mi := &file_proto_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountRequest) ProtoMessage() {}

func (x *ConvertAmountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountRequest.ProtoReflect.Descriptor instead.
func (*ConvertAmountRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertAmountRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConvertAmountRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertAmountRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ConvertAmountResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalAmount  float64                `protobuf:"fixed64,1,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	FromCurrency    string                 `protobuf:"bytes,2,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ConvertedAmount float64                `protobuf:"fixed64,3,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	ToCurrency      string                 `protobuf:"bytes,4,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	RateUsed        float64                `protobuf:"fixed64,5,opt,name=rate_used,json=rateUsed,proto3" json:"rate_used,omitempty"`
	RateTimestamp   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=rate_timestamp,json=rateTimestamp,proto3" json:"rate_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertAmountResponse) Reset() {
	*x = ConvertAmountResponse{}
	mi := &file_proto_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertAmountResponse) ProtoMessage() {}

func (x *ConvertAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertAmountResponse.ProtoReflect.Descriptor instead.
func (*ConvertAmountResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{6}
}

func (x *ConvertAmountResponse) GetOriginalAmount() float64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *ConvertAmountResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertAmountResponse) GetConvertedAmount() float64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertAmountResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ConvertAmountResponse) GetRateUsed() float64 {
	if x != nil {
		return x.RateUsed
	}
	return 0
}

func (x *ConvertAmountResponse) GetRateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.RateTimestamp
	}
	return nil
}

type ConvertMultipleAmountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amounts       []*AmountToConvert     `protobuf:"bytes,1,rep,name=amounts,proto3" json:"amounts,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMultipleAmountsRequest) Reset() {
	*x = ConvertMultipleAmountsRequest{}
	mi := &file_proto_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMultipleAmountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMultipleAmountsRequest) ProtoMessage() {}

func (x *ConvertMultipleAmountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMultipleAmountsRequest.ProtoReflect.Descriptor instead.
func (*ConvertMultipleAmountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{7}
}

func (x *ConvertMultipleAmountsRequest) GetAmounts() []*AmountToConvert {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *ConvertMultipleAmountsRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type AmountToConvert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	FromCurrency  string                 `protobuf:"bytes,3,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AmountToConvert) Reset() {
	*x = AmountToConvert{}
	mi := &file_proto_currency_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AmountToConvert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AmountToConvert) ProtoMessage() {}

func (x *AmountToConvert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AmountToConvert.ProtoReflect.Descriptor instead.
func (*AmountToConvert) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{8}
}

func (x *AmountToConvert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AmountToConvert) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AmountToConvert) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

type ConvertMultipleAmountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Converted     []*ConvertedAmount     `protobuf:"bytes,1,rep,name=converted,proto3" json:"converted,omitempty"`
	Total         float64                `protobuf:"fixed64,2,opt,name=total,proto3" json:"total,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,3,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConvertMultipleAmountsResponse) Reset() {
	*x = ConvertMultipleAmountsResponse{}
	mi := &file_proto_currency_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertMultipleAmountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertMultipleAmountsResponse) ProtoMessage() {}

func (x *ConvertMultipleAmountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertMultipleAmountsResponse.ProtoReflect.Descriptor instead.
func (*ConvertMultipleAmountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{9}
}

func (x *ConvertMultipleAmountsResponse) GetConverted() []*ConvertedAmount {
	if x != nil {
		return x.Converted
	}
	return nil
}

func (x *ConvertMultipleAmountsResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ConvertMultipleAmountsResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ConvertedAmount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OriginalAmount  float64                `protobuf:"fixed64,2,opt,name=original_amount,json=originalAmount,proto3" json:"original_amount,omitempty"`
	FromCurrency    string                 `protobuf:"bytes,3,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ConvertedAmount float64                `protobuf:"fixed64,4,opt,name=converted_amount,json=convertedAmount,proto3" json:"converted_amount,omitempty"`
	RateUsed        float64                `protobuf:"fixed64,5,opt,name=rate_used,json=rateUsed,proto3" json:"rate_used,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConvertedAmount) Reset() {
	*x = ConvertedAmount{}
	mi := &file_proto_currency_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConvertedAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertedAmount) ProtoMessage() {}

func (x *ConvertedAmount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertedAmount.ProtoReflect.Descriptor instead.
func (*ConvertedAmount) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{10}
}

func (x *ConvertedAmount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConvertedAmount) GetOriginalAmount() float64 {
	if x != nil {
		return x.OriginalAmount
	}
	return 0
}

func (x *ConvertedAmount) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ConvertedAmount) GetConvertedAmount() float64 {
	if x != nil {
		return x.ConvertedAmount
	}
	return 0
}

func (x *ConvertedAmount) GetRateUsed() float64 {
	if x != nil {
		return x.RateUsed
	}
	return 0
}

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	DecimalPlaces int32                  `protobuf:"varint,4,opt,name=decimal_places,json=decimalPlaces,proto3" json:"decimal_places,omitempty"`
	IsCrypto      bool                   `protobuf:"varint,5,opt,name=is_crypto,json=isCrypto,proto3" json:"is_crypto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_currency_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{11}
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetDecimalPlaces() int32 {
	if x != nil {
		return x.DecimalPlaces
	}
	return 0
}

func (x *Currency) GetIsCrypto() bool {
	if x != nil {
		return x.IsCrypto
	}
	return false
}

type ListSupportedCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeCrypto bool                   `protobuf:"varint,1,opt,name=include_crypto,json=includeCrypto,proto3" json:"include_crypto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedCurrenciesRequest) Reset() {
	*x = ListSupportedCurrenciesRequest{}
	mi := &file_proto_currency_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedCurrenciesRequest) ProtoMessage() {}

func (x *ListSupportedCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListSupportedCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{12}
}

func (x *ListSupportedCurrenciesRequest) GetIncludeCrypto() bool {
	if x != nil {
		return x.IncludeCrypto
	}
	return false
}

type ListSupportedCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSupportedCurrenciesResponse) Reset() {
	*x = ListSupportedCurrenciesResponse{}
	mi := &file_proto_currency_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSupportedCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSupportedCurrenciesResponse) ProtoMessage() {}

func (x *ListSupportedCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSupportedCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListSupportedCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{13}
}

func (x *ListSupportedCurrenciesResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetRateHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRateHistoryRequest) Reset() {
	*x = GetRateHistoryRequest{}
	mi := &file_proto_currency_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRateHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRateHistoryRequest) ProtoMessage() {}

func (x *GetRateHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRateHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRateHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{14}
}

func (x *GetRateHistoryRequest) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *GetRateHistoryRequest) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *GetRateHistoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetRateHistoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type RateHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,json=fromCurrency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,json=toCurrency,proto3" json:"to_currency,omitempty"`
	History       []*RatePoint           `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateHistoryResponse) Reset() {
	*x = RateHistoryResponse{}
	mi := &file_proto_currency_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateHistoryResponse) ProtoMessage() {}

func (x *RateHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateHistoryResponse.ProtoReflect.Descriptor instead.
func (*RateHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{15}
}

func (x *RateHistoryResponse) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *RateHistoryResponse) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *RateHistoryResponse) GetHistory() []*RatePoint {
	if x != nil {
		return x.History
	}
	return nil
}

type RatePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Rate          float64                `protobuf:"fixed64,2,opt,name=rate,proto3" json:"rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatePoint) Reset() {
	*x = RatePoint{}
	mi := &file_proto_currency_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatePoint) ProtoMessage() {}

func (x *RatePoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatePoint.ProtoReflect.Descriptor instead.
func (*RatePoint) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{16}
}

func (x *RatePoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *RatePoint) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type RefreshRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseCurrency  string                 `protobuf:"bytes,1,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRatesRequest) Reset() {
	*x = RefreshRatesRequest{}
	mi := &file_proto_currency_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRatesRequest) ProtoMessage() {}

func (x *RefreshRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRatesRequest.ProtoReflect.Descriptor instead.
func (*RefreshRatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{17}
}

func (x *RefreshRatesRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

type RefreshRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RatesUpdated  int32                  `protobuf:"varint,2,opt,name=rates_updated,json=ratesUpdated,proto3" json:"rates_updated,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRatesResponse) Reset() {
	*x = RefreshRatesResponse{}
	mi := &file_proto_currency_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRatesResponse) ProtoMessage() {}

func (x *RefreshRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRatesResponse.ProtoReflect.Descriptor instead.
func (*RefreshRatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{18}
}

func (x *RefreshRatesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshRatesResponse) GetRatesUpdated() int32 {
	if x != nil {
		return x.RatesUpdated
	}
	return 0
}

func (x *RefreshRatesResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetLastUpdateTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastUpdateTimeRequest) Reset() {
	*x = GetLastUpdateTimeRequest{}
	mi := &file_proto_currency_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastUpdateTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastUpdateTimeRequest) ProtoMessage() {}

func (x *GetLastUpdateTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastUpdateTimeRequest.ProtoReflect.Descriptor instead.
func (*GetLastUpdateTimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{19}
}

type GetLastUpdateTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastUpdate    *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastUpdateTimeResponse) Reset() {
	*x = GetLastUpdateTimeResponse{}
	mi := &file_proto_currency_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastUpdateTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastUpdateTimeResponse) ProtoMessage() {}

func (x *GetLastUpdateTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastUpdateTimeResponse.ProtoReflect.Descriptor instead.
func (*GetLastUpdateTimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_proto_rawDescGZIP(), []int{20}
}

func (x *GetLastUpdateTimeResponse) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

func (x *GetLastUpdateTimeResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

var File_proto_currency_proto protoreflect.FileDescriptor

const file_proto_currency_proto_rawDesc = "" +
	"\n" +
	"\x14proto/currency.proto\x12\bcurrency\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x01\n" +
	"\fExchangeRate\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"^\n" +
	"\x16GetExchangeRateRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\"B\n" +
	"\x14ExchangeRateResponse\x12*\n" +
	"\x04rate\x18\x01 \x01(\v2\x16.currency.ExchangeRateR\x04rate\"s\n" +
	"\x1fGetMultipleExchangeRatesRequest\x12#\n" +
	"\rbase_currency\x18\x01 \x01(\tR\fbaseCurrency\x12+\n" +
	"\x11target_currencies\x18\x02 \x03(\tR\x10targetCurrencies\"\x89\x02\n" +
	" GetMultipleExchangeRatesResponse\x12#\n" +
	"\rbase_currency\x18\x01 \x01(\tR\fbaseCurrency\x12K\n" +
	"\x05rates\x18\x02 \x03(\v25.currency.GetMultipleExchangeRatesResponse.RatesEntryR\x05rates\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a8\n" +
	"\n" +
	"RatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"t\n" +
	"\x14ConvertAmountRequest\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12#\n" +
	"\rfrom_currency\x18\x02 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x03 \x01(\tR\n" +
	"toCurrency\"\x91\x02\n" +
	"\x15ConvertAmountResponse\x12'\n" +
	"\x0foriginal_amount\x18\x01 \x01(\x01R\x0eoriginalAmount\x12#\n" +
	"\rfrom_currency\x18\x02 \x01(\tR\ffromCurrency\x12)\n" +
	"\x10converted_amount\x18\x03 \x01(\x01R\x0fconvertedAmount\x12\x1f\n" +
	"\vto_currency\x18\x04 \x01(\tR\n" +
	"toCurrency\x12\x1b\n" +
	"\trate_used\x18\x05 \x01(\x01R\brateUsed\x12A\n" +
	"\x0erate_timestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rrateTimestamp\"u\n" +
	"\x1dConvertMultipleAmountsRequest\x123\n" +
	"\aamounts\x18\x01 \x03(\v2\x19.currency.AmountToConvertR\aamounts\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\"^\n" +
	"\x0fAmountToConvert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12#\n" +
	"\rfrom_currency\x18\x03 \x01(\tR\ffromCurrency\"\x90\x01\n" +
	"\x1eConvertMultipleAmountsResponse\x127\n" +
	"\tconverted\x18\x01 \x03(\v2\x19.currency.ConvertedAmountR\tconverted\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x01R\x05total\x12\x1f\n" +
	"\vto_currency\x18\x03 \x01(\tR\n" +
	"toCurrency\"\xb7\x01\n" +
	"\x0fConvertedAmount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0foriginal_amount\x18\x02 \x01(\x01R\x0eoriginalAmount\x12#\n" +
	"\rfrom_currency\x18\x03 \x01(\tR\ffromCurrency\x12)\n" +
	"\x10converted_amount\x18\x04 \x01(\x01R\x0fconvertedAmount\x12\x1b\n" +
	"\trate_used\x18\x05 \x01(\x01R\brateUsed\"\x8e\x01\n" +
	"\bCurrency\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12%\n" +
	"\x0edecimal_places\x18\x04 \x01(\x05R\rdecimalPlaces\x12\x1b\n" +
	"\tis_crypto\x18\x05 \x01(\bR\bisCrypto\"G\n" +
	"\x1eListSupportedCurrenciesRequest\x12%\n" +
	"\x0einclude_crypto\x18\x01 \x01(\bR\rincludeCrypto\"U\n" +
	"\x1fListSupportedCurrenciesResponse\x122\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x12.currency.CurrencyR\n" +
	"currencies\"\xcf\x01\n" +
	"\x15GetRateHistoryRequest\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\x8a\x01\n" +
	"\x13RateHistoryResponse\x12#\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\ffromCurrency\x12\x1f\n" +
	"\vto_currency\x18\x02 \x01(\tR\n" +
	"toCurrency\x12-\n" +
	"\ahistory\x18\x03 \x03(\v2\x13.currency.RatePointR\ahistory\"O\n" +
	"\tRatePoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x12\n" +
	"\x04rate\x18\x02 \x01(\x01R\x04rate\":\n" +
	"\x13RefreshRatesRequest\x12#\n" +
	"\rbase_currency\x18\x01 \x01(\tR\fbaseCurrency\"\x90\x01\n" +
	"\x14RefreshRatesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rrates_updated\x18\x02 \x01(\x05R\fratesUpdated\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x1a\n" +
	"\x18GetLastUpdateTimeRequest\"}\n" +
	"\x19GetLastUpdateTimeResponse\x12;\n" +
	"\vlast_update\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency2\x87\x06\n" +
	"\x0fCurrencyService\x12S\n" +
	"\x0fGetExchangeRate\x12 .currency.GetExchangeRateRequest\x1a\x1e.currency.ExchangeRateResponse\x12q\n" +
	"\x18GetMultipleExchangeRates\x12).currency.GetMultipleExchangeRatesRequest\x1a*.currency.GetMultipleExchangeRatesResponse\x12P\n" +
	"\rConvertAmount\x12\x1e.currency.ConvertAmountRequest\x1a\x1f.currency.ConvertAmountResponse\x12k\n" +
	"\x16ConvertMultipleAmounts\x12'.currency.ConvertMultipleAmountsRequest\x1a(.currency.ConvertMultipleAmountsResponse\x12n\n" +
	"\x17ListSupportedCurrencies\x12(.currency.ListSupportedCurrenciesRequest\x1a).currency.ListSupportedCurrenciesResponse\x12P\n" +
	"\x0eGetRateHistory\x12\x1f.currency.GetRateHistoryRequest\x1a\x1d.currency.RateHistoryResponse\x12M\n" +
	"\fRefreshRates\x12\x1d.currency.RefreshRatesRequest\x1a\x1e.currency.RefreshRatesResponse\x12\\\n" +
	"\x11GetLastUpdateTime\x12\".currency.GetLastUpdateTimeRequest\x1a#.currency.GetLastUpdateTimeResponseB;Z9github.com/radmickey/money-control/backend/proto/currencyb\x06proto3"

var (
	file_proto_currency_proto_rawDescOnce sync.Once
	file_proto_currency_proto_rawDescData []byte
)

func file_proto_currency_proto_rawDescGZIP() []byte {
	file_proto_currency_proto_rawDescOnce.Do(func() {
		file_proto_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_proto_rawDesc), len(file_proto_currency_proto_rawDesc)))
	})
	return file_proto_currency_proto_rawDescData
}

var file_proto_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_currency_proto_goTypes = []any{
	(*ExchangeRate)(nil),                     // 0: currency.ExchangeRate
	(*GetExchangeRateRequest)(nil),           // 1: currency.GetExchangeRateRequest
	(*ExchangeRateResponse)(nil),             // 2: currency.ExchangeRateResponse
	(*GetMultipleExchangeRatesRequest)(nil),  // 3: currency.GetMultipleExchangeRatesRequest
	(*GetMultipleExchangeRatesResponse)(nil), // 4: currency.GetMultipleExchangeRatesResponse
	(*ConvertAmountRequest)(nil),             // 5: currency.ConvertAmountRequest
	(*ConvertAmountResponse)(nil),            // 6: currency.ConvertAmountResponse
	(*ConvertMultipleAmountsRequest)(nil),    // 7: currency.ConvertMultipleAmountsRequest
	(*AmountToConvert)(nil),                  // 8: currency.AmountToConvert
	(*ConvertMultipleAmountsResponse)(nil),   // 9: currency.ConvertMultipleAmountsResponse
	(*ConvertedAmount)(nil),                  // 10: currency.ConvertedAmount
	(*Currency)(nil),                         // 11: currency.Currency
	(*ListSupportedCurrenciesRequest)(nil),   // 12: currency.ListSupportedCurrenciesRequest
	(*ListSupportedCurrenciesResponse)(nil),  // 13: currency.ListSupportedCurrenciesResponse
	(*GetRateHistoryRequest)(nil),            // 14: currency.GetRateHistoryRequest
	(*RateHistoryResponse)(nil),              // 15: currency.RateHistoryResponse
	(*RatePoint)(nil),                        // 16: currency.RatePoint
	(*RefreshRatesRequest)(nil),              // 17: currency.RefreshRatesRequest
	(*RefreshRatesResponse)(nil),             // 18: currency.RefreshRatesResponse
	(*GetLastUpdateTimeRequest)(nil),         // 19: currency.GetLastUpdateTimeRequest
	(*GetLastUpdateTimeResponse)(nil),        // 20: currency.GetLastUpdateTimeResponse
	nil,                                      // 21: currency.GetMultipleExchangeRatesResponse.RatesEntry
	(*timestamppb.Timestamp)(nil),            // 22: google.protobuf.Timestamp
}
var file_proto_currency_proto_depIdxs = []int32{
	22, // 0: currency.ExchangeRate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 1: currency.ExchangeRateResponse.rate:type_name -> currency.ExchangeRate
	21, // 2: currency.GetMultipleExchangeRatesResponse.rates:type_name -> currency.GetMultipleExchangeRatesResponse.RatesEntry
	22, // 3: currency.GetMultipleExchangeRatesResponse.updated_at:type_name -> google.protobuf.Timestamp
	22, // 4: currency.ConvertAmountResponse.rate_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 5: currency.ConvertMultipleAmountsRequest.amounts:type_name -> currency.AmountToConvert
	10, // 6: currency.ConvertMultipleAmountsResponse.converted:type_name -> currency.ConvertedAmount
	11, // 7: currency.ListSupportedCurrenciesResponse.currencies:type_name -> currency.Currency
	22, // 8: currency.GetRateHistoryRequest.start_date:type_name -> google.protobuf.Timestamp
	22, // 9: currency.GetRateHistoryRequest.end_date:type_name -> google.protobuf.Timestamp
	16, // 10: currency.RateHistoryResponse.history:type_name -> currency.RatePoint
	22, // 11: currency.RatePoint.date:type_name -> google.protobuf.Timestamp
	22, // 12: currency.RefreshRatesResponse.updated_at:type_name -> google.protobuf.Timestamp
	22, // 13: currency.GetLastUpdateTimeResponse.last_update:type_name -> google.protobuf.Timestamp
	1,  // 14: currency.CurrencyService.GetExchangeRate:input_type -> currency.GetExchangeRateRequest
	3,  // 15: currency.CurrencyService.GetMultipleExchangeRates:input_type -> currency.GetMultipleExchangeRatesRequest
	5,  // 16: currency.CurrencyService.ConvertAmount:input_type -> currency.ConvertAmountRequest
	7,  // 17: currency.CurrencyService.ConvertMultipleAmounts:input_type -> currency.ConvertMultipleAmountsRequest
	12, // 18: currency.CurrencyService.ListSupportedCurrencies:input_type -> currency.ListSupportedCurrenciesRequest
	14, // 19: currency.CurrencyService.GetRateHistory:input_type -> currency.GetRateHistoryRequest
	17, // 20: currency.CurrencyService.RefreshRates:input_type -> currency.RefreshRatesRequest
	19, // 21: currency.CurrencyService.GetLastUpdateTime:input_type -> currency.GetLastUpdateTimeRequest
	2,  // 22: currency.CurrencyService.GetExchangeRate:output_type -> currency.ExchangeRateResponse
	4,  // 23: currency.CurrencyService.GetMultipleExchangeRates:output_type -> currency.GetMultipleExchangeRatesResponse
	6,  // 24: currency.CurrencyService.ConvertAmount:output_type -> currency.ConvertAmountResponse
	9,  // 25: currency.CurrencyService.ConvertMultipleAmounts:output_type -> currency.ConvertMultipleAmountsResponse
	13, // 26: currency.CurrencyService.ListSupportedCurrencies:output_type -> currency.ListSupportedCurrenciesResponse
	15, // 27: currency.CurrencyService.GetRateHistory:output_type -> currency.RateHistoryResponse
	18, // 28: currency.CurrencyService.RefreshRates:output_type -> currency.RefreshRatesResponse
	20, // 29: currency.CurrencyService.GetLastUpdateTime:output_type -> currency.GetLastUpdateTimeResponse
	22, // [22:30] is the sub-list for method output_type
	14, // [14:22] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_currency_proto_init() }
func file_proto_currency_proto_init() {
	if File_proto_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_proto_rawDesc), len(file_proto_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_proto_goTypes,
		DependencyIndexes: file_proto_currency_proto_depIdxs,
		MessageInfos:      file_proto_currency_proto_msgTypes,
	}.Build()
	File_proto_currency_proto = out.File
	file_proto_currency_proto_goTypes = nil
	file_proto_currency_proto_depIdxs = nil
}
