// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/currency.proto

package currency

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CurrencyService_GetExchangeRate_FullMethodName          = "/currency.CurrencyService/GetExchangeRate"
	CurrencyService_GetMultipleExchangeRates_FullMethodName = "/currency.CurrencyService/GetMultipleExchangeRates"
	CurrencyService_ConvertAmount_FullMethodName            = "/currency.CurrencyService/ConvertAmount"
	CurrencyService_ConvertMultipleAmounts_FullMethodName   = "/currency.CurrencyService/ConvertMultipleAmounts"
	CurrencyService_ListSupportedCurrencies_FullMethodName  = "/currency.CurrencyService/ListSupportedCurrencies"
	CurrencyService_GetRateHistory_FullMethodName           = "/currency.CurrencyService/GetRateHistory"
	CurrencyService_RefreshRates_FullMethodName             = "/currency.CurrencyService/RefreshRates"
	CurrencyService_GetLastUpdateTime_FullMethodName        = "/currency.CurrencyService/GetLastUpdateTime"
)

// CurrencyServiceClient is the client API for CurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CurrencyServiceClient interface {
	GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error)
	GetMultipleExchangeRates(ctx context.Context, in *GetMultipleExchangeRatesRequest, opts ...grpc.CallOption) (*GetMultipleExchangeRatesResponse, error)
	ConvertAmount(ctx context.Context, in *ConvertAmountRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error)
	ConvertMultipleAmounts(ctx context.Context, in *ConvertMultipleAmountsRequest, opts ...grpc.CallOption) (*ConvertMultipleAmountsResponse, error)
	ListSupportedCurrencies(ctx context.Context, in *ListSupportedCurrenciesRequest, opts ...grpc.CallOption) (*ListSupportedCurrenciesResponse, error)
	GetRateHistory(ctx context.Context, in *GetRateHistoryRequest, opts ...grpc.CallOption) (*RateHistoryResponse, error)
	RefreshRates(ctx context.Context, in *RefreshRatesRequest, opts ...grpc.CallOption) (*RefreshRatesResponse, error)
	GetLastUpdateTime(ctx context.Context, in *GetLastUpdateTimeRequest, opts ...grpc.CallOption) (*GetLastUpdateTimeResponse, error)
}

type currencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyServiceClient(cc grpc.ClientConnInterface) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) GetExchangeRate(ctx context.Context, in *GetExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExchangeRateResponse)
	err := c.cc.Invoke(ctx, CurrencyService_GetExchangeRate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) GetMultipleExchangeRates(ctx context.Context, in *GetMultipleExchangeRatesRequest, opts ...grpc.CallOption) (*GetMultipleExchangeRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMultipleExchangeRatesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_GetMultipleExchangeRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) ConvertAmount(ctx context.Context, in *ConvertAmountRequest, opts ...grpc.CallOption) (*ConvertAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertAmountResponse)
	err := c.cc.Invoke(ctx, CurrencyService_ConvertAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) ConvertMultipleAmounts(ctx context.Context, in *ConvertMultipleAmountsRequest, opts ...grpc.CallOption) (*ConvertMultipleAmountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConvertMultipleAmountsResponse)
	err := c.cc.Invoke(ctx, CurrencyService_ConvertMultipleAmounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) ListSupportedCurrencies(ctx context.Context, in *ListSupportedCurrenciesRequest, opts ...grpc.CallOption) (*ListSupportedCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSupportedCurrenciesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_ListSupportedCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) GetRateHistory(ctx context.Context, in *GetRateHistoryRequest, opts ...grpc.CallOption) (*RateHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RateHistoryResponse)
	err := c.cc.Invoke(ctx, CurrencyService_GetRateHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) RefreshRates(ctx context.Context, in *RefreshRatesRequest, opts ...grpc.CallOption) (*RefreshRatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshRatesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_RefreshRates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) GetLastUpdateTime(ctx context.Context, in *GetLastUpdateTimeRequest, opts ...grpc.CallOption) (*GetLastUpdateTimeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLastUpdateTimeResponse)
	err := c.cc.Invoke(ctx, CurrencyService_GetLastUpdateTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyServiceServer is the server API for CurrencyService service.
// All implementations must embed UnimplementedCurrencyServiceServer
// for forward compatibility.
type CurrencyServiceServer interface {
	GetExchangeRate(context.Context, *GetExchangeRateRequest) (*ExchangeRateResponse, error)
	GetMultipleExchangeRates(context.Context, *GetMultipleExchangeRatesRequest) (*GetMultipleExchangeRatesResponse, error)
	ConvertAmount(context.Context, *ConvertAmountRequest) (*ConvertAmountResponse, error)
	ConvertMultipleAmounts(context.Context, *ConvertMultipleAmountsRequest) (*ConvertMultipleAmountsResponse, error)
	ListSupportedCurrencies(context.Context, *ListSupportedCurrenciesRequest) (*ListSupportedCurrenciesResponse, error)
	GetRateHistory(context.Context, *GetRateHistoryRequest) (*RateHistoryResponse, error)
	RefreshRates(context.Context, *RefreshRatesRequest) (*RefreshRatesResponse, error)
	GetLastUpdateTime(context.Context, *GetLastUpdateTimeRequest) (*GetLastUpdateTimeResponse, error)
	mustEmbedUnimplementedCurrencyServiceServer()
}

// UnimplementedCurrencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyServiceServer struct{}

func (UnimplementedCurrencyServiceServer) GetExchangeRate(context.Context, *GetExchangeRateRequest) (*ExchangeRateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExchangeRate not implemented")
}
func (UnimplementedCurrencyServiceServer) GetMultipleExchangeRates(context.Context, *GetMultipleExchangeRatesRequest) (*GetMultipleExchangeRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMultipleExchangeRates not implemented")
}
func (UnimplementedCurrencyServiceServer) ConvertAmount(context.Context, *ConvertAmountRequest) (*ConvertAmountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertAmount not implemented")
}
func (UnimplementedCurrencyServiceServer) ConvertMultipleAmounts(context.Context, *ConvertMultipleAmountsRequest) (*ConvertMultipleAmountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConvertMultipleAmounts not implemented")
}
func (UnimplementedCurrencyServiceServer) ListSupportedCurrencies(context.Context, *ListSupportedCurrenciesRequest) (*ListSupportedCurrenciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSupportedCurrencies not implemented")
}
func (UnimplementedCurrencyServiceServer) GetRateHistory(context.Context, *GetRateHistoryRequest) (*RateHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRateHistory not implemented")
}
func (UnimplementedCurrencyServiceServer) RefreshRates(context.Context, *RefreshRatesRequest) (*RefreshRatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshRates not implemented")
}
func (UnimplementedCurrencyServiceServer) GetLastUpdateTime(context.Context, *GetLastUpdateTimeRequest) (*GetLastUpdateTimeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLastUpdateTime not implemented")
}
func (UnimplementedCurrencyServiceServer) mustEmbedUnimplementedCurrencyServiceServer() {}
func (UnimplementedCurrencyServiceServer) testEmbeddedByValue()                         {}

// UnsafeCurrencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServiceServer will
// result in compilation errors.
type UnsafeCurrencyServiceServer interface {
	mustEmbedUnimplementedCurrencyServiceServer()
}

func RegisterCurrencyServiceServer(s grpc.ServiceRegistrar, srv CurrencyServiceServer) {
	// If the following call panics, it indicates UnimplementedCurrencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyService_ServiceDesc, srv)
}

func _CurrencyService_GetExchangeRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExchangeRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetExchangeRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_GetExchangeRate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetExchangeRate(ctx, req.(*GetExchangeRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_GetMultipleExchangeRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleExchangeRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetMultipleExchangeRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_GetMultipleExchangeRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetMultipleExchangeRates(ctx, req.(*GetMultipleExchangeRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_ConvertAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).ConvertAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_ConvertAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).ConvertAmount(ctx, req.(*ConvertAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_ConvertMultipleAmounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertMultipleAmountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).ConvertMultipleAmounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_ConvertMultipleAmounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).ConvertMultipleAmounts(ctx, req.(*ConvertMultipleAmountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_ListSupportedCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSupportedCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).ListSupportedCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_ListSupportedCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).ListSupportedCurrencies(ctx, req.(*ListSupportedCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_GetRateHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetRateHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_GetRateHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetRateHistory(ctx, req.(*GetRateHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_RefreshRates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).RefreshRates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_RefreshRates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).RefreshRates(ctx, req.(*RefreshRatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_GetLastUpdateTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastUpdateTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetLastUpdateTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_GetLastUpdateTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetLastUpdateTime(ctx, req.(*GetLastUpdateTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyService_ServiceDesc is the grpc.ServiceDesc for CurrencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "currency.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetExchangeRate",
			Handler:    _CurrencyService_GetExchangeRate_Handler,
		},
		{
			MethodName: "GetMultipleExchangeRates",
			Handler:    _CurrencyService_GetMultipleExchangeRates_Handler,
		},
		{
			MethodName: "ConvertAmount",
			Handler:    _CurrencyService_ConvertAmount_Handler,
		},
		{
			MethodName: "ConvertMultipleAmounts",
			Handler:    _CurrencyService_ConvertMultipleAmounts_Handler,
		},
		{
			MethodName: "ListSupportedCurrencies",
			Handler:    _CurrencyService_ListSupportedCurrencies_Handler,
		},
		{
			MethodName: "GetRateHistory",
			Handler:    _CurrencyService_GetRateHistory_Handler,
		},
		{
			MethodName: "RefreshRates",
			Handler:    _CurrencyService_RefreshRates_Handler,
		},
		{
			MethodName: "GetLastUpdateTime",
			Handler:    _CurrencyService_GetLastUpdateTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/currency.proto",
}
