// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/assets.proto

package assets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_STOCK       AssetType = 1
	AssetType_ASSET_TYPE_CRYPTO      AssetType = 2
	AssetType_ASSET_TYPE_ETF         AssetType = 3
	AssetType_ASSET_TYPE_REAL_ESTATE AssetType = 4
	AssetType_ASSET_TYPE_CASH        AssetType = 5
	AssetType_ASSET_TYPE_BOND        AssetType = 6
	AssetType_ASSET_TYPE_COMMODITY   AssetType = 7
	AssetType_ASSET_TYPE_OTHER       AssetType = 8
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_STOCK",
		2: "ASSET_TYPE_CRYPTO",
		3: "ASSET_TYPE_ETF",
		4: "ASSET_TYPE_REAL_ESTATE",
		5: "ASSET_TYPE_CASH",
		6: "ASSET_TYPE_BOND",
		7: "ASSET_TYPE_COMMODITY",
		8: "ASSET_TYPE_OTHER",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_STOCK":       1,
		"ASSET_TYPE_CRYPTO":      2,
		"ASSET_TYPE_ETF":         3,
		"ASSET_TYPE_REAL_ESTATE": 4,
		"ASSET_TYPE_CASH":        5,
		"ASSET_TYPE_BOND":        6,
		"ASSET_TYPE_COMMODITY":   7,
		"ASSET_TYPE_OTHER":       8,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_assets_proto_enumTypes[0].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_proto_assets_proto_enumTypes[0]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{0}
}

type Asset struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubAccountId      string                 `protobuf:"bytes,3,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Symbol            string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name              string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Type              AssetType              `protobuf:"varint,6,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Quantity          float64                `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PurchasePrice     float64                `protobuf:"fixed64,8,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	CurrentPrice      float64                `protobuf:"fixed64,9,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Currency          string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	TotalValue        float64                `protobuf:"fixed64,11,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	ProfitLoss        float64                `protobuf:"fixed64,12,opt,name=profit_loss,json=profitLoss,proto3" json:"profit_loss,omitempty"`
	ProfitLossPercent float64                `protobuf:"fixed64,13,opt,name=profit_loss_percent,json=profitLossPercent,proto3" json:"profit_loss_percent,omitempty"`
	PurchaseDate      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	PriceUpdatedAt    *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=price_updated_at,json=priceUpdatedAt,proto3" json:"price_updated_at,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,18,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_proto_assets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Asset) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Asset) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Asset) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *Asset) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Asset) GetPurchasePrice() float64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *Asset) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *Asset) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Asset) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *Asset) GetProfitLoss() float64 {
	if x != nil {
		return x.ProfitLoss
	}
	return 0
}

func (x *Asset) GetProfitLossPercent() float64 {
	if x != nil {
		return x.ProfitLossPercent
	}
	return 0
}

func (x *Asset) GetPurchaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchaseDate
	}
	return nil
}

func (x *Asset) GetPriceUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PriceUpdatedAt
	}
	return nil
}

func (x *Asset) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Asset) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Asset) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubAccountId  string                 `protobuf:"bytes,2,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Type          AssetType              `protobuf:"varint,5,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PurchasePrice float64                `protobuf:"fixed64,7,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	PurchaseDate  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=purchase_date,json=purchaseDate,proto3" json:"purchase_date,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssetRequest) Reset() {
	*x = CreateAssetRequest{}
	mi := &file_proto_assets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssetRequest) ProtoMessage() {}

func (x *CreateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssetRequest.ProtoReflect.Descriptor instead.
func (*CreateAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAssetRequest) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *CreateAssetRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAssetRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *CreateAssetRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateAssetRequest) GetPurchasePrice() float64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *CreateAssetRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAssetRequest) GetPurchaseDate() *timestamppb.Timestamp {
	if x != nil {
		return x.PurchaseDate
	}
	return nil
}

func (x *CreateAssetRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_proto_assets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{2}
}

func (x *GetAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SubAccountId  string                 `protobuf:"bytes,2,opt,name=sub_account_id,json=subAccountId,proto3" json:"sub_account_id,omitempty"`
	Type          AssetType              `protobuf:"varint,3,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAssetsRequest) Reset() {
	*x = ListAssetsRequest{}
	mi := &file_proto_assets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsRequest) ProtoMessage() {}

func (x *ListAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsRequest.ProtoReflect.Descriptor instead.
func (*ListAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{3}
}

func (x *ListAssetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListAssetsRequest) GetSubAccountId() string {
	if x != nil {
		return x.SubAccountId
	}
	return ""
}

func (x *ListAssetsRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *ListAssetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAssetsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Assets          []*Asset               `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Total           int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page            int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize        int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalValue      float64                `protobuf:"fixed64,5,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalProfitLoss float64                `protobuf:"fixed64,6,opt,name=total_profit_loss,json=totalProfitLoss,proto3" json:"total_profit_loss,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAssetsResponse) Reset() {
	*x = ListAssetsResponse{}
	mi := &file_proto_assets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssetsResponse) ProtoMessage() {}

func (x *ListAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssetsResponse.ProtoReflect.Descriptor instead.
func (*ListAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{4}
}

func (x *ListAssetsResponse) GetAssets() []*Asset {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *ListAssetsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListAssetsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAssetsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAssetsResponse) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *ListAssetsResponse) GetTotalProfitLoss() float64 {
	if x != nil {
		return x.TotalProfitLoss
	}
	return 0
}

type UpdateAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      float64                `protobuf:"fixed64,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PurchasePrice float64                `protobuf:"fixed64,4,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	CurrentPrice  float64                `protobuf:"fixed64,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAssetRequest) Reset() {
	*x = UpdateAssetRequest{}
	mi := &file_proto_assets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAssetRequest) ProtoMessage() {}

func (x *UpdateAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAssetRequest.ProtoReflect.Descriptor instead.
func (*UpdateAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateAssetRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateAssetRequest) GetPurchasePrice() float64 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *UpdateAssetRequest) GetCurrentPrice() float64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *UpdateAssetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAssetRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_proto_assets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAssetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          AssetType              `protobuf:"varint,2,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetPriceRequest) Reset() {
	*x = GetAssetPriceRequest{}
	mi := &file_proto_assets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetPriceRequest) ProtoMessage() {}

func (x *GetAssetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetAssetPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{7}
}

func (x *GetAssetPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetPriceRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

type AssetPriceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price             float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Currency          string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Change_24H        float64                `protobuf:"fixed64,4,opt,name=change_24h,json=change24h,proto3" json:"change_24h,omitempty"`
	ChangePercent_24H float64                `protobuf:"fixed64,5,opt,name=change_percent_24h,json=changePercent24h,proto3" json:"change_percent_24h,omitempty"`
	High_24H          float64                `protobuf:"fixed64,6,opt,name=high_24h,json=high24h,proto3" json:"high_24h,omitempty"`
	Low_24H           float64                `protobuf:"fixed64,7,opt,name=low_24h,json=low24h,proto3" json:"low_24h,omitempty"`
	Volume_24H        float64                `protobuf:"fixed64,8,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	MarketCap         float64                `protobuf:"fixed64,9,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AssetPriceResponse) Reset() {
	*x = AssetPriceResponse{}
	mi := &file_proto_assets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPriceResponse) ProtoMessage() {}

func (x *AssetPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPriceResponse.ProtoReflect.Descriptor instead.
func (*AssetPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{8}
}

func (x *AssetPriceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetPriceResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *AssetPriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AssetPriceResponse) GetChange_24H() float64 {
	if x != nil {
		return x.Change_24H
	}
	return 0
}

func (x *AssetPriceResponse) GetChangePercent_24H() float64 {
	if x != nil {
		return x.ChangePercent_24H
	}
	return 0
}

func (x *AssetPriceResponse) GetHigh_24H() float64 {
	if x != nil {
		return x.High_24H
	}
	return 0
}

func (x *AssetPriceResponse) GetLow_24H() float64 {
	if x != nil {
		return x.Low_24H
	}
	return 0
}

func (x *AssetPriceResponse) GetVolume_24H() float64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *AssetPriceResponse) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *AssetPriceResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type GetMultipleAssetPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queries       []*AssetPriceQuery     `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleAssetPricesRequest) Reset() {
	*x = GetMultipleAssetPricesRequest{}
	mi := &file_proto_assets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleAssetPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleAssetPricesRequest) ProtoMessage() {}

func (x *GetMultipleAssetPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleAssetPricesRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleAssetPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{9}
}

func (x *GetMultipleAssetPricesRequest) GetQueries() []*AssetPriceQuery {
	if x != nil {
		return x.Queries
	}
	return nil
}

type AssetPriceQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          AssetType              `protobuf:"varint,2,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetPriceQuery) Reset() {
	*x = AssetPriceQuery{}
	mi := &file_proto_assets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetPriceQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetPriceQuery) ProtoMessage() {}

func (x *AssetPriceQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetPriceQuery.ProtoReflect.Descriptor instead.
func (*AssetPriceQuery) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{10}
}

func (x *AssetPriceQuery) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetPriceQuery) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

type GetMultipleAssetPricesResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Prices        map[string]*AssetPriceResponse `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FailedSymbols []string                       `protobuf:"bytes,2,rep,name=failed_symbols,json=failedSymbols,proto3" json:"failed_symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleAssetPricesResponse) Reset() {
	*x = GetMultipleAssetPricesResponse{}
	mi := &file_proto_assets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleAssetPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleAssetPricesResponse) ProtoMessage() {}

func (x *GetMultipleAssetPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleAssetPricesResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleAssetPricesResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{11}
}

func (x *GetMultipleAssetPricesResponse) GetPrices() map[string]*AssetPriceResponse {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *GetMultipleAssetPricesResponse) GetFailedSymbols() []string {
	if x != nil {
		return x.FailedSymbols
	}
	return nil
}

type RefreshAssetPricesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AssetIds      []string               `protobuf:"bytes,2,rep,name=asset_ids,json=assetIds,proto3" json:"asset_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAssetPricesRequest) Reset() {
	*x = RefreshAssetPricesRequest{}
	mi := &file_proto_assets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAssetPricesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAssetPricesRequest) ProtoMessage() {}

func (x *RefreshAssetPricesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAssetPricesRequest.ProtoReflect.Descriptor instead.
func (*RefreshAssetPricesRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshAssetPricesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshAssetPricesRequest) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

type RefreshAssetPricesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedCount  int32                  `protobuf:"varint,1,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	FailedIds     []string               `protobuf:"bytes,2,rep,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAssetPricesResponse) Reset() {
	*x = RefreshAssetPricesResponse{}
	mi := &file_proto_assets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAssetPricesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAssetPricesResponse) ProtoMessage() {}

func (x *RefreshAssetPricesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAssetPricesResponse.ProtoReflect.Descriptor instead.
func (*RefreshAssetPricesResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshAssetPricesResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *RefreshAssetPricesResponse) GetFailedIds() []string {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

type GetAssetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          AssetType              `protobuf:"varint,2,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Interval      string                 `protobuf:"bytes,3,opt,name=interval,proto3" json:"interval,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetHistoryRequest) Reset() {
	*x = GetAssetHistoryRequest{}
	mi := &file_proto_assets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetHistoryRequest) ProtoMessage() {}

func (x *GetAssetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetAssetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{14}
}

func (x *GetAssetHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetAssetHistoryRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *GetAssetHistoryRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *GetAssetHistoryRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetAssetHistoryRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type AssetHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	History       []*PricePoint          `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetHistoryResponse) Reset() {
	*x = AssetHistoryResponse{}
	mi := &file_proto_assets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetHistoryResponse) ProtoMessage() {}

func (x *AssetHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetHistoryResponse.ProtoReflect.Descriptor instead.
func (*AssetHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{15}
}

func (x *AssetHistoryResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetHistoryResponse) GetHistory() []*PricePoint {
	if x != nil {
		return x.History
	}
	return nil
}

type PricePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Open          float64                `protobuf:"fixed64,2,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricePoint) Reset() {
	*x = PricePoint{}
	mi := &file_proto_assets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricePoint) ProtoMessage() {}

func (x *PricePoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricePoint.ProtoReflect.Descriptor instead.
func (*PricePoint) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{16}
}

func (x *PricePoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PricePoint) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *PricePoint) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PricePoint) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PricePoint) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *PricePoint) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type GetPortfolioPerformanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,2,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortfolioPerformanceRequest) Reset() {
	*x = GetPortfolioPerformanceRequest{}
	mi := &file_proto_assets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortfolioPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortfolioPerformanceRequest) ProtoMessage() {}

func (x *GetPortfolioPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortfolioPerformanceRequest.ProtoReflect.Descriptor instead.
func (*GetPortfolioPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{17}
}

func (x *GetPortfolioPerformanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPortfolioPerformanceRequest) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetPortfolioPerformanceRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *GetPortfolioPerformanceRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type PortfolioPerformanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalValue        float64                `protobuf:"fixed64,1,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	TotalInvested     float64                `protobuf:"fixed64,2,opt,name=total_invested,json=totalInvested,proto3" json:"total_invested,omitempty"`
	TotalProfitLoss   float64                `protobuf:"fixed64,3,opt,name=total_profit_loss,json=totalProfitLoss,proto3" json:"total_profit_loss,omitempty"`
	ProfitLossPercent float64                `protobuf:"fixed64,4,opt,name=profit_loss_percent,json=profitLossPercent,proto3" json:"profit_loss_percent,omitempty"`
	Currency          string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Allocation        []*AssetAllocation     `protobuf:"bytes,6,rep,name=allocation,proto3" json:"allocation,omitempty"`
	History           []*PerformancePoint    `protobuf:"bytes,7,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PortfolioPerformanceResponse) Reset() {
	*x = PortfolioPerformanceResponse{}
	mi := &file_proto_assets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPerformanceResponse) ProtoMessage() {}

func (x *PortfolioPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPerformanceResponse.ProtoReflect.Descriptor instead.
func (*PortfolioPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{18}
}

func (x *PortfolioPerformanceResponse) GetTotalValue() float64 {
	if x != nil {
		return x.TotalValue
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetTotalInvested() float64 {
	if x != nil {
		return x.TotalInvested
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetTotalProfitLoss() float64 {
	if x != nil {
		return x.TotalProfitLoss
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetProfitLossPercent() float64 {
	if x != nil {
		return x.ProfitLossPercent
	}
	return 0
}

func (x *PortfolioPerformanceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PortfolioPerformanceResponse) GetAllocation() []*AssetAllocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

func (x *PortfolioPerformanceResponse) GetHistory() []*PerformancePoint {
	if x != nil {
		return x.History
	}
	return nil
}

type AssetAllocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          AssetType              `protobuf:"varint,1,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetAllocation) Reset() {
	*x = AssetAllocation{}
	mi := &file_proto_assets_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetAllocation) ProtoMessage() {}

func (x *AssetAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetAllocation.ProtoReflect.Descriptor instead.
func (*AssetAllocation) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{19}
}

func (x *AssetAllocation) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *AssetAllocation) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AssetAllocation) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

type PerformancePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PerformancePoint) Reset() {
	*x = PerformancePoint{}
	mi := &file_proto_assets_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PerformancePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformancePoint) ProtoMessage() {}

func (x *PerformancePoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformancePoint.ProtoReflect.Descriptor instead.
func (*PerformancePoint) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{20}
}

func (x *PerformancePoint) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *PerformancePoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SearchAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type          AssetType              `protobuf:"varint,2,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAssetsRequest) Reset() {
	*x = SearchAssetsRequest{}
	mi := &file_proto_assets_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAssetsRequest) ProtoMessage() {}

func (x *SearchAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAssetsRequest.ProtoReflect.Descriptor instead.
func (*SearchAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{21}
}

func (x *SearchAssetsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchAssetsRequest) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *SearchAssetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AssetSearchResult   `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAssetsResponse) Reset() {
	*x = SearchAssetsResponse{}
	mi := &file_proto_assets_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAssetsResponse) ProtoMessage() {}

func (x *SearchAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAssetsResponse.ProtoReflect.Descriptor instead.
func (*SearchAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{22}
}

func (x *SearchAssetsResponse) GetResults() []*AssetSearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type AssetSearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          AssetType              `protobuf:"varint,3,opt,name=type,proto3,enum=assets.AssetType" json:"type,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetSearchResult) Reset() {
	*x = AssetSearchResult{}
	mi := &file_proto_assets_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSearchResult) ProtoMessage() {}

func (x *AssetSearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assets_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSearchResult.ProtoReflect.Descriptor instead.
func (*AssetSearchResult) Descriptor() ([]byte, []int) {
	return file_proto_assets_proto_rawDescGZIP(), []int{23}
}

func (x *AssetSearchResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *AssetSearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetSearchResult) GetType() AssetType {
	if x != nil {
		return x.Type
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *AssetSearchResult) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *AssetSearchResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_proto_assets_proto protoreflect.FileDescriptor

const file_proto_assets_proto_rawDesc = "" +
	"\n" +
	"\x12proto/assets.proto\x12\x06assets\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x92\x06\n" +
	"\x05Asset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_account_id\x18\x03 \x01(\tR\fsubAccountId\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x06 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x01R\bquantity\x12%\n" +
	"\x0epurchase_price\x18\b \x01(\x01R\rpurchasePrice\x12#\n" +
	"\rcurrent_price\x18\t \x01(\x01R\fcurrentPrice\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12\x1f\n" +
	"\vtotal_value\x18\v \x01(\x01R\n" +
	"totalValue\x12\x1f\n" +
	"\vprofit_loss\x18\f \x01(\x01R\n" +
	"profitLoss\x12.\n" +
	"\x13profit_loss_percent\x18\r \x01(\x01R\x11profitLossPercent\x12?\n" +
	"\rpurchase_date\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\fpurchaseDate\x12D\n" +
	"\x10price_updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x0epriceUpdatedAt\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\bmetadata\x18\x12 \x03(\v2\x1b.assets.Asset.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x03\n" +
	"\x12CreateAssetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_account_id\x18\x02 \x01(\tR\fsubAccountId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x05 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12%\n" +
	"\x0epurchase_price\x18\a \x01(\x01R\rpurchasePrice\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12?\n" +
	"\rpurchase_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\fpurchaseDate\x12D\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2(.assets.CreateAssetRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x0fGetAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xaa\x01\n" +
	"\x11ListAssetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\x0esub_account_id\x18\x02 \x01(\tR\fsubAccountId\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"\xcf\x01\n" +
	"\x12ListAssetsResponse\x12%\n" +
	"\x06assets\x18\x01 \x03(\v2\r.assets.AssetR\x06assets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_value\x18\x05 \x01(\x01R\n" +
	"totalValue\x12*\n" +
	"\x11total_profit_loss\x18\x06 \x01(\x01R\x0ftotalProfitLoss\"\xbc\x02\n" +
	"\x12UpdateAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x01R\bquantity\x12%\n" +
	"\x0epurchase_price\x18\x04 \x01(\x01R\rpurchasePrice\x12#\n" +
	"\rcurrent_price\x18\x05 \x01(\x01R\fcurrentPrice\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.assets.UpdateAssetRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"=\n" +
	"\x12DeleteAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"U\n" +
	"\x14GetAssetPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.assets.AssetTypeR\x04type\"\xd8\x02\n" +
	"\x12AssetPriceResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"change_24h\x18\x04 \x01(\x01R\tchange24h\x12,\n" +
	"\x12change_percent_24h\x18\x05 \x01(\x01R\x10changePercent24h\x12\x19\n" +
	"\bhigh_24h\x18\x06 \x01(\x01R\ahigh24h\x12\x17\n" +
	"\alow_24h\x18\a \x01(\x01R\x06low24h\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\b \x01(\x01R\tvolume24h\x12\x1d\n" +
	"\n" +
	"market_cap\x18\t \x01(\x01R\tmarketCap\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\x1dGetMultipleAssetPricesRequest\x121\n" +
	"\aqueries\x18\x01 \x03(\v2\x17.assets.AssetPriceQueryR\aqueries\"P\n" +
	"\x0fAssetPriceQuery\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.assets.AssetTypeR\x04type\"\xea\x01\n" +
	"\x1eGetMultipleAssetPricesResponse\x12J\n" +
	"\x06prices\x18\x01 \x03(\v22.assets.GetMultipleAssetPricesResponse.PricesEntryR\x06prices\x12%\n" +
	"\x0efailed_symbols\x18\x02 \x03(\tR\rfailedSymbols\x1aU\n" +
	"\vPricesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.assets.AssetPriceResponseR\x05value:\x028\x01\"Q\n" +
	"\x19RefreshAssetPricesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tasset_ids\x18\x02 \x03(\tR\bassetIds\"`\n" +
	"\x1aRefreshAssetPricesResponse\x12#\n" +
	"\rupdated_count\x18\x01 \x01(\x05R\fupdatedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x02 \x03(\tR\tfailedIds\"\xe5\x01\n" +
	"\x16GetAssetHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x1a\n" +
	"\binterval\x18\x03 \x01(\tR\binterval\x129\n" +
	"\n" +
	"start_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\\\n" +
	"\x14AssetHistoryResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12,\n" +
	"\ahistory\x18\x02 \x03(\v2\x12.assets.PricePointR\ahistory\"\xae\x01\n" +
	"\n" +
	"PricePoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\xd0\x01\n" +
	"\x1eGetPortfolioPerformanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\rbase_currency\x18\x02 \x01(\tR\fbaseCurrency\x129\n" +
	"\n" +
	"start_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x125\n" +
	"\bend_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"\xcb\x02\n" +
	"\x1cPortfolioPerformanceResponse\x12\x1f\n" +
	"\vtotal_value\x18\x01 \x01(\x01R\n" +
	"totalValue\x12%\n" +
	"\x0etotal_invested\x18\x02 \x01(\x01R\rtotalInvested\x12*\n" +
	"\x11total_profit_loss\x18\x03 \x01(\x01R\x0ftotalProfitLoss\x12.\n" +
	"\x13profit_loss_percent\x18\x04 \x01(\x01R\x11profitLossPercent\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x127\n" +
	"\n" +
	"allocation\x18\x06 \x03(\v2\x17.assets.AssetAllocationR\n" +
	"allocation\x122\n" +
	"\ahistory\x18\a \x03(\v2\x18.assets.PerformancePointR\ahistory\"n\n" +
	"\x0fAssetAllocation\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"X\n" +
	"\x10PerformancePoint\x12.\n" +
	"\x04date\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04date\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"h\n" +
	"\x13SearchAssetsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x14SearchAssetsResponse\x123\n" +
	"\aresults\x18\x01 \x03(\v2\x19.assets.AssetSearchResultR\aresults\"\x9e\x01\n" +
	"\x11AssetSearchResult\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x04type\x18\x03 \x01(\x0e2\x11.assets.AssetTypeR\x04type\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency*\xde\x01\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ASSET_TYPE_STOCK\x10\x01\x12\x15\n" +
	"\x11ASSET_TYPE_CRYPTO\x10\x02\x12\x12\n" +
	"\x0eASSET_TYPE_ETF\x10\x03\x12\x1a\n" +
	"\x16ASSET_TYPE_REAL_ESTATE\x10\x04\x12\x13\n" +
	"\x0fASSET_TYPE_CASH\x10\x05\x12\x13\n" +
	"\x0fASSET_TYPE_BOND\x10\x06\x12\x18\n" +
	"\x14ASSET_TYPE_COMMODITY\x10\a\x12\x14\n" +
	"\x10ASSET_TYPE_OTHER\x10\b2\xd5\x06\n" +
	"\rAssetsService\x128\n" +
	"\vCreateAsset\x12\x1a.assets.CreateAssetRequest\x1a\r.assets.Asset\x122\n" +
	"\bGetAsset\x12\x17.assets.GetAssetRequest\x1a\r.assets.Asset\x12C\n" +
	"\n" +
	"ListAssets\x12\x19.assets.ListAssetsRequest\x1a\x1a.assets.ListAssetsResponse\x128\n" +
	"\vUpdateAsset\x12\x1a.assets.UpdateAssetRequest\x1a\r.assets.Asset\x12A\n" +
	"\vDeleteAsset\x12\x1a.assets.DeleteAssetRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\rGetAssetPrice\x12\x1c.assets.GetAssetPriceRequest\x1a\x1a.assets.AssetPriceResponse\x12g\n" +
	"\x16GetMultipleAssetPrices\x12%.assets.GetMultipleAssetPricesRequest\x1a&.assets.GetMultipleAssetPricesResponse\x12[\n" +
	"\x12RefreshAssetPrices\x12!.assets.RefreshAssetPricesRequest\x1a\".assets.RefreshAssetPricesResponse\x12O\n" +
	"\x0fGetAssetHistory\x12\x1e.assets.GetAssetHistoryRequest\x1a\x1c.assets.AssetHistoryResponse\x12g\n" +
	"\x17GetPortfolioPerformance\x12&.assets.GetPortfolioPerformanceRequest\x1a$.assets.PortfolioPerformanceResponse\x12I\n" +
	"\fSearchAssets\x12\x1b.assets.SearchAssetsRequest\x1a\x1c.assets.SearchAssetsResponseB9Z7github.com/radmickey/money-control/backend/proto/assetsb\x06proto3"

var (
	file_proto_assets_proto_rawDescOnce sync.Once
	file_proto_assets_proto_rawDescData []byte
)

func file_proto_assets_proto_rawDescGZIP() []byte {
	file_proto_assets_proto_rawDescOnce.Do(func() {
		file_proto_assets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_assets_proto_rawDesc), len(file_proto_assets_proto_rawDesc)))
	})
	return file_proto_assets_proto_rawDescData
}

var file_proto_assets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_assets_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_assets_proto_goTypes = []any{
	(AssetType)(0),                         // 0: assets.AssetType
	(*Asset)(nil),                          // 1: assets.Asset
	(*CreateAssetRequest)(nil),             // 2: assets.CreateAssetRequest
	(*GetAssetRequest)(nil),                // 3: assets.GetAssetRequest
	(*ListAssetsRequest)(nil),              // 4: assets.ListAssetsRequest
	(*ListAssetsResponse)(nil),             // 5: assets.ListAssetsResponse
	(*UpdateAssetRequest)(nil),             // 6: assets.UpdateAssetRequest
	(*DeleteAssetRequest)(nil),             // 7: assets.DeleteAssetRequest
	(*GetAssetPriceRequest)(nil),           // 8: assets.GetAssetPriceRequest
	(*AssetPriceResponse)(nil),             // 9: assets.AssetPriceResponse
	(*GetMultipleAssetPricesRequest)(nil),  // 10: assets.GetMultipleAssetPricesRequest
	(*AssetPriceQuery)(nil),                // 11: assets.AssetPriceQuery
	(*GetMultipleAssetPricesResponse)(nil), // 12: assets.GetMultipleAssetPricesResponse
	(*RefreshAssetPricesRequest)(nil),      // 13: assets.RefreshAssetPricesRequest
	(*RefreshAssetPricesResponse)(nil),     // 14: assets.RefreshAssetPricesResponse
	(*GetAssetHistoryRequest)(nil),         // 15: assets.GetAssetHistoryRequest
	(*AssetHistoryResponse)(nil),           // 16: assets.AssetHistoryResponse
	(*PricePoint)(nil),                     // 17: assets.PricePoint
	(*GetPortfolioPerformanceRequest)(nil), // 18: assets.GetPortfolioPerformanceRequest
	(*PortfolioPerformanceResponse)(nil),   // 19: assets.PortfolioPerformanceResponse
	(*AssetAllocation)(nil),                // 20: assets.AssetAllocation
	(*PerformancePoint)(nil),               // 21: assets.PerformancePoint
	(*SearchAssetsRequest)(nil),            // 22: assets.SearchAssetsRequest
	(*SearchAssetsResponse)(nil),           // 23: assets.SearchAssetsResponse
	(*AssetSearchResult)(nil),              // 24: assets.AssetSearchResult
	nil,                                    // 25: assets.Asset.MetadataEntry
	nil,                                    // 26: assets.CreateAssetRequest.MetadataEntry
	nil,                                    // 27: assets.UpdateAssetRequest.MetadataEntry
	nil,                                    // 28: assets.GetMultipleAssetPricesResponse.PricesEntry
	(*timestamppb.Timestamp)(nil),          // 29: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 30: google.protobuf.Empty
}
var file_proto_assets_proto_depIdxs = []int32{
	0,  // 0: assets.Asset.type:type_name -> assets.AssetType
	29, // 1: assets.Asset.purchase_date:type_name -> google.protobuf.Timestamp
	29, // 2: assets.Asset.price_updated_at:type_name -> google.protobuf.Timestamp
	29, // 3: assets.Asset.created_at:type_name -> google.protobuf.Timestamp
	29, // 4: assets.Asset.updated_at:type_name -> google.protobuf.Timestamp
	25, // 5: assets.Asset.metadata:type_name -> assets.Asset.MetadataEntry
	0,  // 6: assets.CreateAssetRequest.type:type_name -> assets.AssetType
	29, // 7: assets.CreateAssetRequest.purchase_date:type_name -> google.protobuf.Timestamp
	26, // 8: assets.CreateAssetRequest.metadata:type_name -> assets.CreateAssetRequest.MetadataEntry
	0,  // 9: assets.ListAssetsRequest.type:type_name -> assets.AssetType
	1,  // 10: assets.ListAssetsResponse.assets:type_name -> assets.Asset
	27, // 11: assets.UpdateAssetRequest.metadata:type_name -> assets.UpdateAssetRequest.MetadataEntry
	0,  // 12: assets.GetAssetPriceRequest.type:type_name -> assets.AssetType
	29, // 13: assets.AssetPriceResponse.updated_at:type_name -> google.protobuf.Timestamp
	11, // 14: assets.GetMultipleAssetPricesRequest.queries:type_name -> assets.AssetPriceQuery
	0,  // 15: assets.AssetPriceQuery.type:type_name -> assets.AssetType
	28, // 16: assets.GetMultipleAssetPricesResponse.prices:type_name -> assets.GetMultipleAssetPricesResponse.PricesEntry
	0,  // 17: assets.GetAssetHistoryRequest.type:type_name -> assets.AssetType
	29, // 18: assets.GetAssetHistoryRequest.start_date:type_name -> google.protobuf.Timestamp
	29, // 19: assets.GetAssetHistoryRequest.end_date:type_name -> google.protobuf.Timestamp
	17, // 20: assets.AssetHistoryResponse.history:type_name -> assets.PricePoint
	29, // 21: assets.PricePoint.timestamp:type_name -> google.protobuf.Timestamp
	29, // 22: assets.GetPortfolioPerformanceRequest.start_date:type_name -> google.protobuf.Timestamp
	29, // 23: assets.GetPortfolioPerformanceRequest.end_date:type_name -> google.protobuf.Timestamp
	20, // 24: assets.PortfolioPerformanceResponse.allocation:type_name -> assets.AssetAllocation
	21, // 25: assets.PortfolioPerformanceResponse.history:type_name -> assets.PerformancePoint
	0,  // 26: assets.AssetAllocation.type:type_name -> assets.AssetType
	29, // 27: assets.PerformancePoint.date:type_name -> google.protobuf.Timestamp
	0,  // 28: assets.SearchAssetsRequest.type:type_name -> assets.AssetType
	24, // 29: assets.SearchAssetsResponse.results:type_name -> assets.AssetSearchResult
	0,  // 30: assets.AssetSearchResult.type:type_name -> assets.AssetType
	9,  // 31: assets.GetMultipleAssetPricesResponse.PricesEntry.value:type_name -> assets.AssetPriceResponse
	2,  // 32: assets.AssetsService.CreateAsset:input_type -> assets.CreateAssetRequest
	3,  // 33: assets.AssetsService.GetAsset:input_type -> assets.GetAssetRequest
	4,  // 34: assets.AssetsService.ListAssets:input_type -> assets.ListAssetsRequest
	6,  // 35: assets.AssetsService.UpdateAsset:input_type -> assets.UpdateAssetRequest
	7,  // 36: assets.AssetsService.DeleteAsset:input_type -> assets.DeleteAssetRequest
	8,  // 37: assets.AssetsService.GetAssetPrice:input_type -> assets.GetAssetPriceRequest
	10, // 38: assets.AssetsService.GetMultipleAssetPrices:input_type -> assets.GetMultipleAssetPricesRequest
	13, // 39: assets.AssetsService.RefreshAssetPrices:input_type -> assets.RefreshAssetPricesRequest
	15, // 40: assets.AssetsService.GetAssetHistory:input_type -> assets.GetAssetHistoryRequest
	18, // 41: assets.AssetsService.GetPortfolioPerformance:input_type -> assets.GetPortfolioPerformanceRequest
	22, // 42: assets.AssetsService.SearchAssets:input_type -> assets.SearchAssetsRequest
	1,  // 43: assets.AssetsService.CreateAsset:output_type -> assets.Asset
	1,  // 44: assets.AssetsService.GetAsset:output_type -> assets.Asset
	5,  // 45: assets.AssetsService.ListAssets:output_type -> assets.ListAssetsResponse
	1,  // 46: assets.AssetsService.UpdateAsset:output_type -> assets.Asset
	30, // 47: assets.AssetsService.DeleteAsset:output_type -> google.protobuf.Empty
	9,  // 48: assets.AssetsService.GetAssetPrice:output_type -> assets.AssetPriceResponse
	12, // 49: assets.AssetsService.GetMultipleAssetPrices:output_type -> assets.GetMultipleAssetPricesResponse
	14, // 50: assets.AssetsService.RefreshAssetPrices:output_type -> assets.RefreshAssetPricesResponse
	16, // 51: assets.AssetsService.GetAssetHistory:output_type -> assets.AssetHistoryResponse
	19, // 52: assets.AssetsService.GetPortfolioPerformance:output_type -> assets.PortfolioPerformanceResponse
	23, // 53: assets.AssetsService.SearchAssets:output_type -> assets.SearchAssetsResponse
	43, // [43:54] is the sub-list for method output_type
	32, // [32:43] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_proto_assets_proto_init() }
func file_proto_assets_proto_init() {
	if File_proto_assets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_assets_proto_rawDesc), len(file_proto_assets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_assets_proto_goTypes,
		DependencyIndexes: file_proto_assets_proto_depIdxs,
		EnumInfos:         file_proto_assets_proto_enumTypes,
		MessageInfos:      file_proto_assets_proto_msgTypes,
	}.Build()
	File_proto_assets_proto = out.File
	file_proto_assets_proto_goTypes = nil
	file_proto_assets_proto_depIdxs = nil
}
