// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/assets.proto

package assets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AssetsService_CreateAsset_FullMethodName             = "/assets.AssetsService/CreateAsset"
	AssetsService_GetAsset_FullMethodName                = "/assets.AssetsService/GetAsset"
	AssetsService_ListAssets_FullMethodName              = "/assets.AssetsService/ListAssets"
	AssetsService_UpdateAsset_FullMethodName             = "/assets.AssetsService/UpdateAsset"
	AssetsService_DeleteAsset_FullMethodName             = "/assets.AssetsService/DeleteAsset"
	AssetsService_GetAssetPrice_FullMethodName           = "/assets.AssetsService/GetAssetPrice"
	AssetsService_GetMultipleAssetPrices_FullMethodName  = "/assets.AssetsService/GetMultipleAssetPrices"
	AssetsService_RefreshAssetPrices_FullMethodName      = "/assets.AssetsService/RefreshAssetPrices"
	AssetsService_GetAssetHistory_FullMethodName         = "/assets.AssetsService/GetAssetHistory"
	AssetsService_GetPortfolioPerformance_FullMethodName = "/assets.AssetsService/GetPortfolioPerformance"
	AssetsService_SearchAssets_FullMethodName            = "/assets.AssetsService/SearchAssets"
)

// AssetsServiceClient is the client API for AssetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssetsServiceClient interface {
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error)
	UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*Asset, error)
	DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetAssetPrice(ctx context.Context, in *GetAssetPriceRequest, opts ...grpc.CallOption) (*AssetPriceResponse, error)
	GetMultipleAssetPrices(ctx context.Context, in *GetMultipleAssetPricesRequest, opts ...grpc.CallOption) (*GetMultipleAssetPricesResponse, error)
	RefreshAssetPrices(ctx context.Context, in *RefreshAssetPricesRequest, opts ...grpc.CallOption) (*RefreshAssetPricesResponse, error)
	GetAssetHistory(ctx context.Context, in *GetAssetHistoryRequest, opts ...grpc.CallOption) (*AssetHistoryResponse, error)
	GetPortfolioPerformance(ctx context.Context, in *GetPortfolioPerformanceRequest, opts ...grpc.CallOption) (*PortfolioPerformanceResponse, error)
	SearchAssets(ctx context.Context, in *SearchAssetsRequest, opts ...grpc.CallOption) (*SearchAssetsResponse, error)
}

type assetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssetsServiceClient(cc grpc.ClientConnInterface) AssetsServiceClient {
	return &assetsServiceClient{cc}
}

func (c *assetsServiceClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetsService_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) GetAsset(ctx context.Context, in *GetAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetsService_GetAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) ListAssets(ctx context.Context, in *ListAssetsRequest, opts ...grpc.CallOption) (*ListAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetsResponse)
	err := c.cc.Invoke(ctx, AssetsService_ListAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) UpdateAsset(ctx context.Context, in *UpdateAssetRequest, opts ...grpc.CallOption) (*Asset, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Asset)
	err := c.cc.Invoke(ctx, AssetsService_UpdateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) DeleteAsset(ctx context.Context, in *DeleteAssetRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AssetsService_DeleteAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) GetAssetPrice(ctx context.Context, in *GetAssetPriceRequest, opts ...grpc.CallOption) (*AssetPriceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetPriceResponse)
	err := c.cc.Invoke(ctx, AssetsService_GetAssetPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) GetMultipleAssetPrices(ctx context.Context, in *GetMultipleAssetPricesRequest, opts ...grpc.CallOption) (*GetMultipleAssetPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMultipleAssetPricesResponse)
	err := c.cc.Invoke(ctx, AssetsService_GetMultipleAssetPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) RefreshAssetPrices(ctx context.Context, in *RefreshAssetPricesRequest, opts ...grpc.CallOption) (*RefreshAssetPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshAssetPricesResponse)
	err := c.cc.Invoke(ctx, AssetsService_RefreshAssetPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) GetAssetHistory(ctx context.Context, in *GetAssetHistoryRequest, opts ...grpc.CallOption) (*AssetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssetHistoryResponse)
	err := c.cc.Invoke(ctx, AssetsService_GetAssetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) GetPortfolioPerformance(ctx context.Context, in *GetPortfolioPerformanceRequest, opts ...grpc.CallOption) (*PortfolioPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortfolioPerformanceResponse)
	err := c.cc.Invoke(ctx, AssetsService_GetPortfolioPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assetsServiceClient) SearchAssets(ctx context.Context, in *SearchAssetsRequest, opts ...grpc.CallOption) (*SearchAssetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAssetsResponse)
	err := c.cc.Invoke(ctx, AssetsService_SearchAssets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssetsServiceServer is the server API for AssetsService service.
// All implementations must embed UnimplementedAssetsServiceServer
// for forward compatibility.
type AssetsServiceServer interface {
	CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error)
	GetAsset(context.Context, *GetAssetRequest) (*Asset, error)
	ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error)
	UpdateAsset(context.Context, *UpdateAssetRequest) (*Asset, error)
	DeleteAsset(context.Context, *DeleteAssetRequest) (*emptypb.Empty, error)
	GetAssetPrice(context.Context, *GetAssetPriceRequest) (*AssetPriceResponse, error)
	GetMultipleAssetPrices(context.Context, *GetMultipleAssetPricesRequest) (*GetMultipleAssetPricesResponse, error)
	RefreshAssetPrices(context.Context, *RefreshAssetPricesRequest) (*RefreshAssetPricesResponse, error)
	GetAssetHistory(context.Context, *GetAssetHistoryRequest) (*AssetHistoryResponse, error)
	GetPortfolioPerformance(context.Context, *GetPortfolioPerformanceRequest) (*PortfolioPerformanceResponse, error)
	SearchAssets(context.Context, *SearchAssetsRequest) (*SearchAssetsResponse, error)
	mustEmbedUnimplementedAssetsServiceServer()
}

// UnimplementedAssetsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAssetsServiceServer struct{}

func (UnimplementedAssetsServiceServer) CreateAsset(context.Context, *CreateAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedAssetsServiceServer) GetAsset(context.Context, *GetAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAsset not implemented")
}
func (UnimplementedAssetsServiceServer) ListAssets(context.Context, *ListAssetsRequest) (*ListAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAssets not implemented")
}
func (UnimplementedAssetsServiceServer) UpdateAsset(context.Context, *UpdateAssetRequest) (*Asset, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAsset not implemented")
}
func (UnimplementedAssetsServiceServer) DeleteAsset(context.Context, *DeleteAssetRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAsset not implemented")
}
func (UnimplementedAssetsServiceServer) GetAssetPrice(context.Context, *GetAssetPriceRequest) (*AssetPriceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetPrice not implemented")
}
func (UnimplementedAssetsServiceServer) GetMultipleAssetPrices(context.Context, *GetMultipleAssetPricesRequest) (*GetMultipleAssetPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMultipleAssetPrices not implemented")
}
func (UnimplementedAssetsServiceServer) RefreshAssetPrices(context.Context, *RefreshAssetPricesRequest) (*RefreshAssetPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshAssetPrices not implemented")
}
func (UnimplementedAssetsServiceServer) GetAssetHistory(context.Context, *GetAssetHistoryRequest) (*AssetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssetHistory not implemented")
}
func (UnimplementedAssetsServiceServer) GetPortfolioPerformance(context.Context, *GetPortfolioPerformanceRequest) (*PortfolioPerformanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortfolioPerformance not implemented")
}
func (UnimplementedAssetsServiceServer) SearchAssets(context.Context, *SearchAssetsRequest) (*SearchAssetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAssets not implemented")
}
func (UnimplementedAssetsServiceServer) mustEmbedUnimplementedAssetsServiceServer() {}
func (UnimplementedAssetsServiceServer) testEmbeddedByValue()                       {}

// UnsafeAssetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssetsServiceServer will
// result in compilation errors.
type UnsafeAssetsServiceServer interface {
	mustEmbedUnimplementedAssetsServiceServer()
}

func RegisterAssetsServiceServer(s grpc.ServiceRegistrar, srv AssetsServiceServer) {
	// If the following call panics, it indicates UnimplementedAssetsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AssetsService_ServiceDesc, srv)
}

func _AssetsService_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_GetAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).GetAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_GetAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).GetAsset(ctx, req.(*GetAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_ListAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).ListAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_ListAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).ListAssets(ctx, req.(*ListAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_UpdateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).UpdateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_UpdateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).UpdateAsset(ctx, req.(*UpdateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_DeleteAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).DeleteAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_DeleteAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).DeleteAsset(ctx, req.(*DeleteAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_GetAssetPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).GetAssetPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_GetAssetPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).GetAssetPrice(ctx, req.(*GetAssetPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_GetMultipleAssetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleAssetPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).GetMultipleAssetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_GetMultipleAssetPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).GetMultipleAssetPrices(ctx, req.(*GetMultipleAssetPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_RefreshAssetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshAssetPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).RefreshAssetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_RefreshAssetPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).RefreshAssetPrices(ctx, req.(*RefreshAssetPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_GetAssetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).GetAssetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_GetAssetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).GetAssetHistory(ctx, req.(*GetAssetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_GetPortfolioPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).GetPortfolioPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_GetPortfolioPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).GetPortfolioPerformance(ctx, req.(*GetPortfolioPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssetsService_SearchAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssetsServiceServer).SearchAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AssetsService_SearchAssets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssetsServiceServer).SearchAssets(ctx, req.(*SearchAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AssetsService_ServiceDesc is the grpc.ServiceDesc for AssetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AssetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "assets.AssetsService",
	HandlerType: (*AssetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAsset",
			Handler:    _AssetsService_CreateAsset_Handler,
		},
		{
			MethodName: "GetAsset",
			Handler:    _AssetsService_GetAsset_Handler,
		},
		{
			MethodName: "ListAssets",
			Handler:    _AssetsService_ListAssets_Handler,
		},
		{
			MethodName: "UpdateAsset",
			Handler:    _AssetsService_UpdateAsset_Handler,
		},
		{
			MethodName: "DeleteAsset",
			Handler:    _AssetsService_DeleteAsset_Handler,
		},
		{
			MethodName: "GetAssetPrice",
			Handler:    _AssetsService_GetAssetPrice_Handler,
		},
		{
			MethodName: "GetMultipleAssetPrices",
			Handler:    _AssetsService_GetMultipleAssetPrices_Handler,
		},
		{
			MethodName: "RefreshAssetPrices",
			Handler:    _AssetsService_RefreshAssetPrices_Handler,
		},
		{
			MethodName: "GetAssetHistory",
			Handler:    _AssetsService_GetAssetHistory_Handler,
		},
		{
			MethodName: "GetPortfolioPerformance",
			Handler:    _AssetsService_GetPortfolioPerformance_Handler,
		},
		{
			MethodName: "SearchAssets",
			Handler:    _AssetsService_SearchAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/assets.proto",
}
